### ISSUE TITLE
xWebConfigKeyValue does not handle existing appsettings correctly

### ISSUE THREAD

**Issue by bdanse** [PowerShell/xWebAdministration#107]
Hi,
I am trying to use xWebConfigKeyValue to modify an existing set of appsettings. 
The service is installed through a package and already has some existing appsettings in place.
But trying to alter these values results in the same value in all value attributes. 

Looks like the Modify-Item function filters on value only. Resulting in changes on every setting with an empty value. 
`$filter= "$defaultFilter/add[@$propertyName=`'$oldValue`']"`

But missing the $key value in that function to fix it. And I'm not sure if adding it would break something.

Appsettings that need to be changed

```
 <add key="WEB_SERVICE_SDK_AUTHENTICATION_USERNAME" value=""/>
 <add key="WEB_SERVICE_SDK_AUTHENTICATION_PASSWORD" value=""/>
```

Used DSC 

```
        xWebConfigKeyValue setMobileSdkUserName
        {
            Ensure = "Present"
            ConfigSection = "AppSettings"
            Key = "WEB_SERVICE_SDK_AUTHENTICATION_USERNAME"
            Value = $mfaCreds.UserName
            IsAttribute = $false
            WebsitePath = "IIS:\sites\" + $siteName + "\" + $mfaMobileApp
            DependsOn = @("[xPackage]installMobileAppService")
        }
```

**Comment by tysonjhayes** [comment]
What version of the module are you using? I don't think I've run into this issue in particular, and I've been modifying existing keys. Though I believe mine already have values. I'll have to play with it to see if I can repro.

**Comment by bdanse** [comment]
@tysonjhayes I am using version 1.9.0.0. But checked the 1.10.0.0 code is the same. 
Indeed works fine with an appsetting with a default value already set.
