### ISSUE TITLE
Create a function to generate the BindingInfo

### ISSUE THREAD

**Issue by gigi81** [PowerShell/xWebAdministration#113]
I'm trying to create a function that returns the bindinginfo for a website. This is intended to reduce the complexity of my dsc resource file that will have 20/30 websites with similar bindinginfo based on the node name. Below is what I have at the moment but I'm getting an error and I don't know exactly how to sort it out. Any help on this would be really appreciated.

This is what I have at the moment:

`
configuration DscTest
{
	Import-DscResource -ModuleName xWebAdministration;
	
	Node localhost
	{
		xWebsite TestWebSite
		{
			Ensure = "Present"
			Name = "TestWebSite"
			PhysicalPath = "C:\inetpub\test"
			BindingInfo = (Get-TestBindingInformation $Node)
		}
	}
}

function Get-TestBindingInformation
{
	[OutputType([Microsoft.Management.Infrastructure.CimInstance[]])]
	param(
		[System.Collections.Hashtable] $node
	)
	
	return @(
		New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
			Port                  = 80
			Protocol              = "HTTP"
			HostName              = "test1"
		} -ClientOnly

		New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
			Port                  = 80
			Protocol              = "HTTP"
			HostName              = "test2"
		} -ClientOnly
	)
}

DscTest
`

And this is the error I get:

Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" argument(s): 
"Convert property 'BindingInfo' value from type 'STRING[]' to type 'INSTANCE[]' failed                                          
 At line:22, char:2                                                                                                             
 Buffer:                                                                                                                        
onName = "DscTest";                                                                                                             
};^                                                                                                                             
insta                                                                                                                           
"                                                                                                                               
At C:\windows\system32\windowspowershell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2193 char:21 
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...                                                 
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException                                    
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

**Comment by tysonjhayes** [comment]
I'll admit I'm kind of at a loss with this one, @TravisEz13 @PlagueHO any ideas?

**Comment by PlagueHO** [comment]
@tysonjhayes - actually I might have some ideas - I ran into some problems like this when implementing unit tests for the cFSRM resources (creating CIM instances and passing them around functions). I'll have a play around and see if I can see anything.

**Comment by PlagueHO** [comment]
I looked back through all my old cFSRM stuff and found that I had to do away with Embedded Instance arrays because the only way I could get them to work was to hard code them into the config. At the time I gave up and worked around the problem. I don't like mysteries so I decided to dig a bit further into it - this is a long read:

-Test 1: The following code works just fine:
```powershell
configuration DscTest
{
    Import-DscResource -ModuleName xWebAdministration;

    Node localhost
    {
        xWebsite TestWebSite
        {
            Ensure = "Present"
            Name = "TestWebSite"
            PhysicalPath = "C:\inetpub\test"
            BindingInfo = @(
                MSFT_xWebBindingInformation
                {
                    Port                  = 80
                    Protocol              = "HTTP"
                    HostName              = "test1"
                }           
                MSFT_xWebBindingInformation
                {
                    Port                  = 80
                    Protocol              = "HTTP"
                    HostName              = "test2"
                }
            )
        }
    }
}
DscTest
```

- Test 2: This looks like it works - **but it does not add the actual binding object**. So the MOF is valid but has no binding info:
```powershell
configuration DscTest
{
    Import-DscResource -ModuleName xWebAdministration;

    Node localhost
    {
        $Obj1 = New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
            Port                  = 80
            Protocol              = "HTTP"
            HostName              = "test1"
        } -ClientOnly
        xWebsite TestWebSite
        {
            Ensure = "Present"
            Name = "TestWebSite"
            PhysicalPath = "C:\inetpub\test"
            BindingInfo = $Obj1
        }
    }
}
DscTest
```

 - Test 3: This breaks with the error @Gigi81 sees:
```powershell
configuration DscTest
{
    Import-DscResource -ModuleName xWebAdministration;

    Node localhost
    {
        $Obj1 = New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
            Port                  = 80
            Protocol              = "HTTP"
            HostName              = "test1"
        } -ClientOnly
        $Obj2 = New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
            Port                  = 80
            Protocol              = "HTTP"
            HostName              = "test2"
        } -ClientOnly

        xWebsite TestWebSite
        {
            Ensure = "Present"
            Name = "TestWebSite"
            PhysicalPath = "C:\inetpub\test"
            BindingInfo = @($Obj1,$Obj2)
        }
    }
}
DscTest
```
The error is reported to occur when this is called:
[Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache]::ValidateInstanceText($instanceText)

Looking at the $instanceText in all 3 of the above situations we can see the problem with the MOF generation:
- Test 1 MOF (trimmed out unimportant stuff):
```
instance of MSFT_xWebBindingInformation as $MSFT_xWebBindingInformation1ref
{
Port = 80;
 Protocol = "http";
 HostName = "test1";

};

instance of MSFT_xWebBindingInformation as $MSFT_xWebBindingInformation2ref
{
Port = 80;
 Protocol = "http";
 HostName = "test2";

};

instance of MSFT_xWebsite as $MSFT_xWebsite1ref
{
ResourceID = "[xWebsite]TestWebSite";
 PhysicalPath = "C:\\inetpub\\test";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Dan\\Downloads\\DscTest.ps1::7::9::xWebsite";
 Name = "TestWebSite";
 ModuleName = "xWebAdministration";
 BindingInfo = {
    $MSFT_xWebBindingInformation1ref,
    $MSFT_xWebBindingInformation2ref
};
 ModuleVersion = "1.10.0.0";
```

- Test 2 MOF:
```
instance of MSFT_xWebsite as $MSFT_xWebsite1ref
{
ResourceID = "[xWebsite]TestWebSite";
 PhysicalPath = "C:\\inetpub\\test";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Dan\\Downloads\\DscTest.ps1::12::9::xWebsite";
 Name = "TestWebSite";
 ModuleName = "xWebAdministration";
 ModuleVersion = "1.10.0.0";
```

- Test 3 MOF:
```
instance of MSFT_xWebsite as $MSFT_xWebsite1ref
{
ResourceID = "[xWebsite]TestWebSite";
 PhysicalPath = "C:\\inetpub\\test";
 Ensure = "Present";
 SourceInfo = "C:\\Users\\Dan\\Downloads\\DscTest.ps1::18::9::xWebsite";
 Name = "TestWebSite";
 ModuleName = "xWebAdministration";
 BindingInfo = {
    "MSFT_xWebBindingInformation",
    "MSFT_xWebBindingInformation"
};
 ModuleVersion = "1.10.0.0";
```

So, we can see the MOF is clearly not generated correctly if the objects that are passed to an Embedded Instance is contained in a variable.

I might try to dig a little deeper into this, but I think this needs to go up as an issue on UserVoice.

**Comment by gigi81** [comment]
Hi guys,
Thanks very much for taking the time to have a look into this, particularly to @PlagueHO for the detailed answer.
As suggested I opened a UserVoice here:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13496448-bug-cim-instances-are-not-compiled-correctly-into
Feel free to upvote.

**Comment by TravisEz13** [comment]
I think this question was answered.  You filed a UserVoice for the desired language feature.  So, I'm closing the issue.

**Comment by PlagueHO** [comment]
Cool! Thanks @gigi81 - have voted for it.
