### ISSUE TITLE
Can't run tests unless in root module folder

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#117]
Right now you can only run pester tests if you are in the root folder of the module, but we want to be able to run tests while inside a folder (like 'Unit' for example).

**Comment by KarolKaczmarek** [comment]
Agreed, we should be able to run it from any folder (root/tests/integration/unit)

**Comment by KarolKaczmarek** [comment]
This is follow up to: https://github.com/PowerShell/xWebAdministration/pull/111
