### ISSUE TITLE
xWebsite SSL Binding set certificate fails with "Value does not fall within the expected range."

### ISSUE THREAD

**Issue by striker24JB** [PowerShell/xWebAdministration#121]
Using xWebsite to configure an SSL binding and set the certificate on a domain-joined web server running Windows 2012 R2 Standard.

When resource gets to the portion where it has to set the certificate it errors out with "Value does not fall within the expected range."

If I manually change the $Properties.certificateHash in the set-target to the certificate thumbprint or store it manually in a variable, it works ($certHash = "_hash_" works, but $certHash = $Properties.certificateHash doesn't even with $certHash type forcibly set to string via [string]$certHash.)  

Works : 
$certHash = "_hash_"
$Binding.AddSslCertificate($certHash, $Properties.certificateStoreName)

Works:
$Binding.AddSslCertificate("_hash_", $Properties.certificateStoreName)

Doesn't Work : 
[string]$certHash = $Properties.certificateHash
$Binding.AddSslCertificate($certHash, $Properties.certificateStoreName)

Doesn't Work (Original): 
$Binding.AddSslCertificate($Properties.certificateHash, $Properties.certificateStoreName)

It looks like $Properties.certificateHash itself is set properly, value wise.(verified by doing a write-verbose $Properties.certificateHash just before the call).

**Comment by striker24JB** [comment]
After experimenting, I believe I've figured out what the culprit is (still don't know why it's being caused).

I'm using Powershell 5.0 RTM in the environment.

It seems that when ConvertTo-WebBinding parses the BindingInfo, for certificateThumbPrint it inserts a Unicode Left-To-Right character at the beginning (8206).  This causes the total length of the string to be 1 larger than intended (how I discovered it).

I solved it by creating a doing $CertificateThumbprint = $Binding.CertificateThumbprint -replace '[\W],'' to strip out any weird characters.
Then change from $OutputObject.Add('certificateHash', $Binding.CertificateThumbprint) to $OutputObject.Add('certificateHash', [String]$CertificateThumbPrint)

I stll can't figure out why it inserts the LTR character in the beginning though.

**Comment by SNikalaichyk** [comment]
Hi,
Most probably the **Unicode**-encoded thumbprint was copied from the **Certificate** window.

![certgui](https://cloud.githubusercontent.com/assets/13381926/14921889/3581160a-0e3d-11e6-933d-5b019eb108b4.jpg)

In **Notepad++** convert you script to **ANSI**. You can use **Notepad** too, but the file must be reopened. You should see something like this:

![encoding](https://cloud.githubusercontent.com/assets/13381926/14921780/a4ba501e-0e3c-11e6-8b1f-87dd8e69934c.jpg)

Remove it and you should be fine.

**Comment by tysonjhayes** [comment]
Hi @striker24JB  @SNikalaichyk has submitted a fix for this which we've merged. As noted you can remove the character manually or if you update to dev latest it will remove the character for you. As this looks to be resolved I'm going to go ahead and close this. Please reopen if you are still having issues or need more assistance.
