### ISSUE TITLE
xWebAppPool missing SetProfileEnvironment property

### ISSUE THREAD

**Issue by mpalomas** [PowerShell/xWebAdministration#122]
Hello,

Since IIS 8.0, a SetProfileEnvironment was introduced on processModel, but apparently it's missing from your xWebAppPool (I get error saying member SetProfileEnvironment is not valid)

http://www.iis.net/configreference/system.applicationhost/applicationpools/add/processmodel

So I would consider this as a bug.

**Comment by SNikalaichyk** [comment]
Hi,
Not all the properties are currently supported.
Support for setting the **setProfileEnvironment** property has been recently added in #98. Pull request is currently Opened but hopefully we'll get it merged soon.

**Comment by mpalomas** [comment]
Very nice to hear, thanks!

**Comment by tysonjhayes** [comment]
PR was merged. Can you please see if this resolves your issue?

**Comment by mpalomas** [comment]
yes, issue solved, many thanks

**Comment by tysonjhayes** [comment]
Thanks for letting us know!
