### ISSUE TITLE
xWebAppPool removes existing credentials if not specified

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xWebAdministration#128]
**Issue Description:**

Consider the below configuration example:

    xWebAppPool AppPoolExample {
        Name = "My existing app pool name"
        restartSchedule = @("03:00:00")
    }

Here I am trying to only manage the time of the app pool schedule of an app pool that is created elsewhere (in this case SharePoint is creating the app pool). When I run the resource described above it sets the time on the app pool correctly, but it also changes the run as account from the specific domain account that SharePoint provisioned the app pool to use back to the default "ApplicationPoolIdentity" value, which breaks the app pool completely.

**Expected Behavior**

The xAppPoolResource should only change the restart schedule and leave the existing value for the run as account alone in this scenario.

**Environment details**

 * Windows Server 2012 R2
 * WMF 5.0 RTM

**Comment by tysonjhayes** [comment]
What version of the resource are you using? We've recently made osme changes to that resource in particular.

**Comment by tysonjhayes** [comment]
Specifically we actually removed the default value for that in the dev version.

**Comment by BrianFarnhill** [comment]
@tysonjhayes I knew I left something out - I'm running 1.9.0.0 that I think I pulled from the PSGallery

**Comment by BrianFarnhill** [comment]
@tysonjhayes You're right, I can see the defaults in that build. Happy to close this one seeing as its been fixed in dev. Thanks dude

**Comment by tysonjhayes** [comment]
Awesome, glad I could help. :grin:
