### ISSUE TITLE
MSFT_xWebBindingInformation certificate store values are incorrect

### ISSUE THREAD

**Issue by arkasha** [PowerShell/xWebAdministration#13]
MSFT_xWebsite.schema.mof contains "Person" and "WebHosting" certificate store names.

Personal is not actually the certificate store name and needs to be changed to "My". Here is my machine cert store list:
```
gci Cert:\LocalMachine\ | select Name

Name
----
TrustedPublisher
ClientAuthIssuer
Remote Desktop
Root
TrustedDevices
WebHosting <-- This shows up as "Web Hosting" in MMC
CA
Windows Live ID Token Issuer
REQUEST
AuthRoot
FlightRoot
TrustedPeople
My <-- This shows up as "Personal" in MMC
SmartCardRoot
Trust
Disallowed
SMS
```

**Comment by vors** [comment]
Is it the same problem as https://github.com/PowerShell/xWebAdministration/pull/11 ?

**Comment by arkasha** [comment]
Yes it is.

**Comment by TravisEz13** [comment]
fixed by Pull Request #11

**Comment by arkasha** [comment]
That pull request was closed though.

**Comment by TravisEz13** [comment]
Pull Request #16 resolved and is merged to dev
