### ISSUE TITLE
Invoke-Expression used in xWebAppPool

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#154]
Invoke-Expression is used 3 times in this resource. Since this command is vulnerable to PS injection attacks, it shouldn't be used. The code where Invoke-Expression is used needs to be re-worked to not use this command.
Where it's used:
line 153: $returnValue.Add($_.Name, (Invoke-Expression -Command ('$appPool.{0}' -f $_.Path)))
line 361: $PSBoundParameters[$propertyName] -ne
                        (Invoke-Expression -Command ('$appPool.{0}' -f $propertyPath))
line 724: $PSBoundParameters[$propertyName] -ne
                    (Invoke-Expression -Command ('$appPool.{0}' -f $propertyPath))

**Comment by mbreakey3** [comment]
@SNikalaichyk  - could you take a look at these? I'm having trouble figuring out an alternative way to write these pieces of code without invoke-expression

**Comment by tysonjhayes** [comment]
Do we have a broader discussion going about not using Invoke-Expression?

**Comment by mbreakey3** [comment]
So, for the actual resources we've decided that Invoke-Expression cannot be used due to the security risks. I'm working on figuring out some of the workarounds as the fix varies depending on the context, but it's difficult in some of these cases since I'm not as familiar with what the code does

**Comment by SNikalaichyk** [comment]
DSC resources are not even signed. It means you cannot ensure code integrity and anyone can inject anything into .PSM1 files without even using Invoke-Expression. In my opinion it's completely fine to use it.

**Comment by mbreakey3** [comment]
In order to ensure that this code is secure and reliable, we have to remove Invoke-Expressions in all of the resources before xWebAdministration can be considered a high quality resource and not just an experimental one.

Here are a couple links describing more in detail why we shouldn't use it:
https://powershellstation.com/2015/12/09/code-smell-invoke-expression/
https://blogs.msdn.microsoft.com/powershell/2011/06/03/invoke-expression-considered-harmful/

**Comment by SNikalaichyk** [comment]
There is no easy way to get rid of it in xWebAppPool. It works really well in this specific scenario.

**Comment by mbreakey3** [comment]
We're looking into some possible alternatives

**Comment by tysonjhayes** [comment]
So again, I ask do we have a broader discussion around this? Seems kind of arbitrary to decide that we don't want invoke-expression in DSC resources without discussing it broadly amongst all of our resources, furthermore it would invite discussions around what some more secure alternatives could be.

**Comment by mbreakey3** [comment]
Yeah, @KarolKaczmarek @TravisEz13 any input on this?

**Comment by mbreakey3** [comment]
Also, the fix for this has been implemented in PR #161
