### ISSUE TITLE
Get rid of Invoke-Expression commands in Integration tests

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#156]
Since Invoke-Expression is vulnerable to PS injection attacks, it shouldn't be used. The code where Invoke-Expression is used needs to be re-worked to not use this command.

Where it's used:

**xIISFeatureDelegation.Integration.Tests:**
line 84: Invoke-Expression -Command "$($script:DSCResourceName)_DenyDelegation -OutputPath `$TestEnvironment.WorkingFolder"

**xIISHandler.Integration.Tests:**
line35:Invoke-Expression -Command "$($script:DSCResourceName)_RemoveHandler -OutputPath `$TestEnvironment.WorkingFolder"

line 52: Invoke-Expression -Command "$($script:DSCResourceName)_AddHandler -OutputPath `$TestEnvironment.WorkingFolder"

line 63: Invoke-Expression -Command "$($script:DSCResourceName)_StaticFileHandler -OutputPath `$TestEnvironment.WorkingFolder"

**xIISMimeTypeMapping.Integration.Tests:**
lines 35, 52, 68, 78

**xWebAppPool.Integration.Tests:**
line 48

**xWebAppPoolDefaults.Integration.Tests:**
lines: 46, 73, 102, 126, 143

**xWebsiteDefaults.Integration.Tests:**
lines 34, 57

**Comment by mbreakey3** [comment]
@tysonjhayes and @SNikalaichyk would you mind taking a look at these?

**Comment by tysonjhayes** [comment]
Are we really that worried about an injection attack on our integration tests? Also are there any suggestions on what we should be using instead?

**Comment by mbreakey3** [comment]
Just had a discussion about this. So for now, we're not going to worry about the invoke-expressions in the tests, so I'm going to close this issue for now. Sorry for the confusion
