### ISSUE TITLE
todo comments/commented out code in xIisModule.psm1

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#157]
-Any updates on this 'bug' in both Get and Set TargetResource. can we delete this comment?
       " # bug(TBD) deal with this better, maybe a seperate resource...."

-As well as this line of commented out code in Get-TargetResource:
"#-and $Module -ieq $handler.Module"

**Comment by tysonjhayes** [comment]
Probably, to be entirely honest I'm not 100% sure what that module is for...

**Comment by mbreakey3** [comment]
@KarolKaczmarek Do you have any background on this? It looks like it was transferred over when this resource was moved to gitHub

**Comment by KarolKaczmarek** [comment]
I'm not the author, but the second comment can be removed.
Regarding the first one... it was created before open sourcing, you may want to follow up with @grayzu, @TravisEz13 or Arun (don't know his GitHub handle) since they have been originally working on xWebAdministration.
