### ISSUE TITLE
Authenticationinfo setting does not work on xWebSite level

### ISSUE THREAD

**Issue by rs38** [PowerShell/xWebAdministration#164]
setting:

    xWebSite IISWebSite
    {
    AuthenticationInfo =  MSFT_xWebAuthenticationInformation  
            {
            Anonymous = $true
            Basic = $false
            Windows = $true
            Digest = $false
            }}

throws:
VERBOSE: [WEBIE00056]: LCM:  [ Start  Test     ]  [[xWebsite]IISWebSite]
_Error: Unrecognized configuration path 'MACHINE/WEBROOT/APPHOST/Microsoft.IIs.PowerShell.Framework.ConfigurationElement'
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.IIs.PowerShell.Provider.GetConfigurationPropertyCommand_

whereas on the Web Application level it works fine:

    xWebApplication WebApplication
    {
     AuthenticationInfo =  MSFT_xWebApplicationAuthenticationInformation
            {
            Anonymous = $true
            Basic = $false
            Windows = $true
            Digest = $false
            }}

**Comment by rs38** [comment]
also I do not quite understand the mixed occurance of MSFT_xWeb**Application**AuthenticationInformation
and MSFT_xWebAuthenticationInformation in this test:  
https://github.com/PowerShell/xWebAdministration/blob/master/Tests/Unit/MSFT_xWebsite.Tests.ps1

**Comment by rs38** [comment]
retested it with MSFT_xWebsite.psm1 from the DEV branch and the error is fixed.
probably this one:
https://github.com/PowerShell/xWebAdministration/pull/131

**Comment by guitarrapc** [comment]
I also met this problem. Thanks you tracking.
