### ISSUE TITLE
Is there Milestone to release 1.12.0.0?

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/xWebAdministration#169]
Hi, I've complete test with 1.11.0.0 for my environment and find xWebSite and other have to be update to unreleased version.

Is there any plan date to release next xWebAdministration module?

**Comment by TravisEz13** [comment]
@kwirkykat ?

**Comment by guitarrapc** [comment]
Already released and close.

**Comment by TravisEz13** [comment]
@guitarrapc Thanks
