### ISSUE TITLE
When WebAdministration module is not installed xWebSite throws an error saying it performed an interactive operation

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xWebAdministration#17]

**Comment by TravisEz13** [comment]
Pull Request #16 added a test, which is passing for this, but should fail.
[See line 19](https://github.com/PowerShell/xWebAdministration/blob/dev/Tests/MSFT_xWebBindingInformation.Tests.ps1#L19)

**Comment by tysonjhayes** [comment]
Assign it to me I'll need to get a VM up with WMF 5.0 anyway for some testing I'm doing in xNetworking so I'll be able to repro it.

**Comment by TravisEz13** [comment]
Consider it assigned Tyson, but I cannot assign it... I'll follow up

**Comment by tysonjhayes** [comment]
This is fixed though I'm not sure when.
