### ISSUE TITLE
No examples for xWebApplication

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#190]
At least one example file needs to be added to show how to use this resource.

**Comment by kevinsea** [comment]
I just wanted to point out that this [DSC generator](https://github.com/kevinsea/dsc-generator) can quickly give you some good, ready-to-run examples based on your current IIS configuration.

![dsc-gen2](https://cloud.githubusercontent.com/assets/3883668/17835220/f5fc5868-672f-11e6-814c-dd1354f7ac5e.PNG)

**Comment by mbreakey3** [comment]
Great, thank you for bringing this to my attention.
