### ISSUE TITLE
Create a short pre-run script for Examples

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#212]
There should be a script that ensures the machine is set up and ready to run any/all of the examples. i.e. making sure IIS is installed.

**Comment by jrudley** [comment]
Sounds like a good case for DSC:)

**Comment by johlju** [comment]
I think we should use the integration tests for this instead. Integration tests should be used to configure all or most aspects of the resource so users can validate the resources in a an environment of their choice. 

I label this as discussion instead so the community can decide what is the best option for this.
