### ISSUE TITLE
AuthenticationInfo property of xWebsite fails.

### ISSUE THREAD

**Issue by BarnumD** [PowerShell/xWebAdministration#217]
Given example DSC code:
>Configuration My_Website
{
  Import-DscResource -Module xWebAdministration
  Node mynode
  {
    xWebsite example.domain.com
    {
      Ensure          = "Present"
      Name            = "example.domain.com"
      State           = "Started"
      PhysicalPath    = "C:\inetpub\example.domain.com\webroot"
	  AuthenticationInfo     = @(
                MSFT_xWebAuthenticationInformation
                {
                    Anonymous  = $false
                    Basic      = $false
                    Digest     = $false
                    Windows    = $true
                }
            )
    }
  }
}

The task fails when calling My_Website from powershell.
>Write-NodeMOFFile : Invalid MOF definition for node 'mynode': Exception calling "ValidateInstanceText" with "1"
argument(s): "Convert property 'AuthenticationInfo' value from type 'INSTANCE[]' to type 'INSTANCE' failed
 At line:31, char:2
 Buffer:
ame = "My_Website";
};^
insta

I was trying to set this up via puppet.  See [here](http://stackoverflow.com/questions/39026601/puppet-dsc-module-could-not-evaluate-convert-property-authenticationinfo-val). But i was getting the same type of error.  I tried the module version 1.13 directly through powershell dsc and got the same error.

**Comment by BarnumD** [comment]
>        AuthenticationInfo = 
                 MSFT_xWebAuthenticationInformation 
                 {
                      Anonymous = $true
                      Basic = $false
                      Digest = $false
                      Windows = $false
                 }

Using AuthenticationInfo without the @() seems to work.  Perhaps the issue here is that both binding info and authentication info are documented as needing to be " in the form of an array" but actually authenticationinfo does not?

**Comment by kevinsea** [comment]
I was trying to get @BarnumD on stackoverflow, see #223 for my notes on the documentation issue.

**Comment by BarnumD** [comment]
Thanks for letting me know and raising the issue.
