### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by sameer-kumar** [PowerShell/xWebAdministration#218]
I have installed **xWebAdministration** v 1.13.0.0 on my source server using Install-Module command. Then I copied the folder 1.13.0.0 folder from my source server to target node under C:\Program Files\WindowsPowerShell\Modules\xWebAdministration folder. 
When I try to run a DSC configuration which is referencing resources from this module, I get not found error,`Unable to load module 'xWebAdministration': module not found.`

On my target node, if I execute this statement, `$m = Get-Module -ListAvailable xwebadministration` then $m is null. However, $m is returned with valid object on my source server.

P.S. My source server is running WMF5.0 RTM and my target is 2012R2 (POSH 4.0)

Am I missing something?
Thanks!

**Comment by kwirkykat** [comment]
@sameer-kumar WMF/PowerShell 4.0 doesn't like the version folder. Copy the contents of the 1.13.0.0 folder one level up into the C:\Program Files\WindowsPowerShell\Modules\xWebAdministration folder and then delete the 1.13.0.0 folder.

**Comment by tysonjhayes** [comment]
Hey @sameer-kumar - as we haven't heard from you in a while I'm going to close this issue, if you are still having an issue please feel free to reopen this.
