### ISSUE TITLE
xWebsite MOF error on Windows 7

### ISSUE THREAD

**Issue by rfresow** [PowerShell/xWebAdministration#226]
xWebsite 1.13.0.0 returns an error on Windows 7:

_The command Test-TargetResource of the PS module MSFT_xwebsite does not implement the write property LogPath mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\DscResources\MSFT_xWebsite\MSFT_xWebsite.schema.mof. All write parameters mentioned in the schema file must be implemented by the command Test-TargetResource._

$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
Test code:
```
Configuration Test_xWebAdministration {
    Import-DscResource -ModuleName xWebAdministration

    Node localhost {
        xWebsite DefaultSite {
            Name = "Default Web Site"
            State = "Started"
            PhysicalPath = "C:\inetpub\wwwroot"
        }
    }
}

Test_xWebAdministration -OutputPath "$env:TEMP\Test_xWebAdministration"
Start-DscConfiguration "$env:TEMP\Test_xWebAdministration\" -Wait -Verbose
```
Works fine on W10, W2008-R2 and W2012, not on W7.

**Comment by kwirkykat** [comment]
@mbreakey3 or @tysonjhayes Any idea what's happening here?

**Comment by tysonjhayes** [comment]
@rfresow - did you upgrade from an older version of xWebAdministration? Have you rebooted the system since this error? When I've run into this before it was an issue with WMI having a cached older version which was fixed by either stopping WMI or a reboot. Not the best answer I know but I've never been able to figure out exactly what's going on. :/

**Comment by rfresow** [comment]
@tysonjhayes I didn't do a reboot after installing. Just tested with installing the latest version and rebooting and it seems that it is working now. On an other machine we have a similar problem with a mof mismatch and probably rebooting that machine will resolve that problem also. Too bad it needs a reboot because we want to be able to install a resource on the fly.

**Comment by tysonjhayes** [comment]
I've gotten away with just crashing WMI and not needing to do a full reboot. I think the bug is in WMF 4.0 as I've never heard of a complaint on 5.0 with the upgrade process...
