### ISSUE TITLE
Adding bindings takes ages then Central Certificate store is enabled

### ISSUE THREAD

**Issue by TomasKT** [PowerShell/xWebAdministration#231]
Hi Devs!

So here is a thing...

We have like ~300 bindings attached to the IIS website. 

Every time we push DSC it takes 15min to do the job. 

However, If I change Central Certificate store path to something that it's not valid, it adds bindings in a less than a minute. 

Question would be why it takes so long to add bindings then Central Certificate store is "enabled"? 

Would it be possible to make a workaround to shorten the time of adding bindings?

**Comment by kwirkykat** [comment]
@tysonjhayes Any idea here?

**Comment by tysonjhayes** [comment]
@TomasKT - Couple of quick questions.

1) Which version of the module are you using?
2) Does it take 15 mins when there is no change to make? ie: It's just running test with no set? Or is it making changes and takes 15 minutes to apply to all of this.  This would just change what code it would be executing.
3) Could you give us a sample of the config so we are trying to repro a similar problem? I think just one to three bindings would probably be fine?  I'm trying to get a sense of what you are throwing at it.

**Comment by TomasKT** [comment]
1) 1.12.0.0
2) It takes 15min regardless if there are changes or not. Also I did some more testing and discovered that Central cred store doesn't make any difference, it still takes 15min. Apologies for miss guiding. 
We could change case in to "Deployment takes the same amount of time with or without changes in the configuration". 
3) I have added two files, deployment and data. I have left just IIS configuration related code.
https://github.com/TomasKT/xWebAdministration

**Comment by tysonjhayes** [comment]
So what I'm understanding is you have ~300 bindings and its taking about 15 mins, which you feel is to long? In the original issue you indicated you could make it go faster, is that no longer the case?  Is the issue you are discussing boiling down to its taking to long?

**Comment by TomasKT** [comment]
I don't mind that it takes 15min for a very first time than it's being deployed on new server. But for other next deployments it should take less time, since all bindings are there. So, it feels that it doesn't check if binding is there or not... 
It could  not make it run faster, I was confused with other stuff that i was working. As I said, I did more testing and all test took 15min.
Ideally we would like to have a code which would check which bindings exist and does changes accordingly. As for now it does blindly without checking if binding exist.

**Comment by tysonjhayes** [comment]
> Ideally we would like to have a code which would check which bindings exist and does changes accordingly. As for now it does blindly without checking if binding exist.

I'm a bit confused by the above statement [L879](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L879) shows the following code:

````powershell
        if ($PSBoundParameters.ContainsKey('BindingInfo') -and `
            $null -ne $BindingInfo)
        {
            if (-not (Test-WebsiteBinding -Name $Name -BindingInfo $BindingInfo))
            {
                $inDesiredState = $false
                Write-Verbose -Message ($LocalizedData.VerboseTestTargetFalseBindingInfo `
                                        -f $Name)
            }
        }
````

Which shows we test that changes are needed every time in the test-targetresource function.

On [L536](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L536) we show the folowing:
````powershell
            if ($PSBoundParameters.ContainsKey('BindingInfo') -and `
                $null -ne $BindingInfo)
            {
                if (-not (Test-WebsiteBinding -Name $Name `
                                              -BindingInfo $BindingInfo))
                {
                    Update-WebsiteBinding -Name $Name -BindingInfo $BindingInfo
                    Write-Verbose -Message ($LocalizedData.VerboseSetTargetUpdatedBindingInfo `
                                            -f $Name)
                }
            }
````

I interpret this code as checking the bindings exist  and need to be changed before making changes. If you are experiencing something different I would like to see your output so we can look at that as it shouldn't be changing anything without a diff in the bindings.

**Comment by TomasKT** [comment]
Is it possible that binding check takes the same amount of time as adding a change? 

That would explain why it's takes same amount of time.

**Comment by johlju** [comment]
It seems it first run through evaluation so that the binding information is correct; https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1830
Then it get the web site using `Get-WebSite` to get the current binding information and compare it to the one provided and tested above; https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1933

Could it be that the Get-WebStie call was the one that took time?
