### ISSUE TITLE
New resource X509-Certificate?

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xWebAdministration#235]
I am thinking about creating a DSC resource for a SSL/TLS server certificate, it would ensure that for a certain https binding of a certain web site a valid certificate would always be present.

Right now I'm using a PowerShell script which in turn uses the [AcmeSharp PowerShell module](https://github.com/ebekker/ACMESharp) to request a new Let's Encrypt certificate if the existing one expires in x days.

While it would be nice to have such a resource inside xWebAdministration, I feel that it may not fit because: 1. It requires a third party open source PowerShell module to work, and 2. it requires some registration with the CA provider upfront. Even though it may be possible to include the registration in the resource itself. 

Any thoughts about this? Would it be valuable for people? Does it fit in here, or should I just create my own project for such a DSC resource?

**Comment by PlagueHO** [comment]
Hi @hahndorf - if you need to request an SSL certificate from a CA using DSC, why not use xCertReq from [xCertificate](https://github.com/PowerShell/xCertificate)? That is the one we use.

However, getting the certificate issued is one thing, binding it to the site is something else - because you won't know the thumbprint of the certificate up front. [This issue](https://github.com/PowerShell/xWebAdministration/issues/201) refers to this problem.

If you were going to create a new resource specifically for something relating only to certificates (and not IIS), xCertificate would be the location to put it IMHO.

**Comment by hahndorf** [comment]
Hi PlagueHO, I just saw the open issue about this after submit this one. I was under the impression xCertReq would only work with a local Windows CA, but not with something like Let's Encrypt or possible other automated providers.
What I was thinking of is requesting a new certificate from Let's Encrypt, installing it and then assigning it to the correct web binding where it is needed. So it plays into IIS as well as the more general Windows certificate store.

**Comment by PlagueHO** [comment]
Hi @hahndorf  - You are correct, xCertReq only supports requesting from a Windows CA. I'm not familiar with Let's Encrypt. Does it produce an x.509 certificate that can then be imported into the Windows Certificate Store? xCertificate does have a resource for importing x.509 or PFX files into the Windows Certificate Store where they can then be bound to IIS. So I guess missing piece of the puzzle would be the certificate issuance by Let's Encrypt. If you were going to write a resource for that I'd definitely recommend putting it in xCertificate though. Again, HTH! :smile:

**Comment by hahndorf** [comment]
This is what my current [script](https://github.com/hahndorf/hacops/blob/master/Update-LECertificate.ps1) does:
- Looping through all SSLBindings in IIS and finding the associated X509 certificate, check for expiry date, if the cert is about to expire in x days, it requests a new certificate from the Let's encrypt CA, it waits for one being issued, it then imports it into the Windows certificate store and assigns the new cert to the original SSL binding. This all happens fully automated. So I thought it would be nice to put that into a DSC resource. It could be using xCertificate but it is very IIS related.

**Comment by kwirkykat** [comment]
@hahndorf I agree with @PlagueHO. If a new resource if needed here, it should go in xCertificate.

**Comment by ccsandrew** [comment]
I would be in need of this feature in the near future - but I'm a DSC newbie so this is a bit of a shot in the dark: 

Does it make sense to optionally allow xWebsites' bindinginfo managed object to optionally accept a xCertReq object?  It seems that all the details you would need to intelligently select the desired cert are there, and you could kill two birds with one configuration (e.g. your cert request and your IIS website binding).  You could even keep the Thumbprint field - it can be a self-signed cert fallback should your xCertReq object fail.  

Jeez, I hope I'm making sense this late in the day.

**Comment by johlju** [comment]
@ccsandrew You can use xCertReq to issue the certificate and install it into the certificate store. Then use xWebSites to find the certificate using subject name for example. If you need further help, please open a new issue.

**Comment by johlju** [comment]
Closing this issue since such resource module should be added to the resource module https://github.com/PowerShell/CertificateDsc
