### ISSUE TITLE
Error Converting Boolean to String

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/xWebAdministration#244]
I'm importing version 1.14.0.0 into my config and have a setting like this

```
xWebAppPool PSWAPool 
        {
            Ensure                = "Present"
            Name                  = $PSWAppPoolName
            autoStart             = $True
            managedRuntimeVersion = "v4.0"
            managedPipelineMode   = "Integrated"
            startMode             = "AlwaysRunning"
            identityType          = "ApplicationPoolIdentity"
            restartSchedule       = @("18:30:00","05:00:00")
            DependsOn             = @('[WindowsFeature]IIS','[WindowsFeature]AspNet45') 
        }
```

Which as far as I can tell is the correct syntax. But when I try to run it I get this error:

```
Exception calling "ValidateInstanceText" with "1" argument(s): "Convert 
property 'autoStart' value from type 'BOOLEAN' to type 'STRING' failed
 At line:213, char:2
```

Any suggestions or should I roll back to a previous version when Autostart was a string?

**Comment by jdhitsolutions** [comment]
Well I sort of resolved this but it might point to a larger bug in DSC. My configuration was explicitly importing the latest version even though I also had 2 previous versions installed. I uninstalled the older versions and then my config ran as expected. PowerShell appeared to be using the older schemas which was causing a problem.

**Comment by kwirkykat** [comment]
@jdhitsolutions What WMF/PowerShell version are you using?

**Comment by jdhitsolutions** [comment]
I was authoring on a Windows 10 box with some build of 5.1. I think Windows updated since I posted this.

**Comment by johlju** [comment]
@jdhitsolutions I closing this due to age. If this is still a problem then please reopen or if someone else has this problem, then please comment. Thanks!
