### ISSUE TITLE
LogPath does not match and will be updated on Website "Default Web Site".

### ISSUE THREAD

**Issue by lalanc01** [PowerShell/xWebAdministration#256]
Hi, while trying to use the xWebsite resource to set the log path for the Default Website, it tells me that the log path is correctly set, but then right after tells me that it's not and that it'll update it.

The log path gets updated correctly if I ever change it to something else, to verify that the resource works, but this breaks my validation has it always returns false because of this, Here how the verbose looks like (attached image):

![dsc](https://cloud.githubusercontent.com/assets/23404903/20222531/a508a2d0-a803-11e6-851c-118f631cf829.jpg)

Is that normal behavior?

Thks in advance and don't hesitate if you have any questions.

Steph

**Comment by remcoeissing** [comment]
I looked at this and it's caused by an incorrect check on `$website.logfile.logPath`. This should be changed to `$website.logfile.directory`. I will add some extra tests and change the incorrect statements and offer a pull request to fix this.
