### ISSUE TITLE
Parameter 'PhysicalPath' must point to an existing path

### ISSUE THREAD

**Issue by liquorc** [PowerShell/xWebAdministration#288]
Hello, 

When I try to run a dsc creating website and webapplications with physical paths that point to a network path. I receive the following error:

PowerShell DSC resource MSFT_xWebsite  failed to execute Set-TargetResource functionality with error message: Failure to successfully create the website "website". Error: "Parameter 'PhysicalPath' should point to existing path.".
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : computername

Is there anyway of resolving this issue? Pointing the physical path to a local path works without any issue.

Thanks.

**Comment by liquorc** [comment]
In testing, if I manually create the website with any physical path and run the dsc, it does modify the physical path field in the desired state using the UNC path. It seems like when it is creating a new website this parameter fails. The same happens with xWebApplication as well.

**Comment by dreams3290** [comment]
hi, how did you fix this?
