### ISSUE TITLE
xWebApplication EnabledProtocols

### ISSUE THREAD

**Issue by thomppg** [PowerShell/xWebAdministration#297]
I have downloaded version 1.17.0.0. And when trying to apply multiple protocols EnabledProtocols = @('http','net.tcp'), it just doesn't work.  If I just include net.tcp. DSC doesn't apply this change to the webapplicationWith verbose logging turned on, I see that it detects that the web application is not in the desired state and tries to update it, but the protocol stays as http and is not updated.

I also tried running the sample web application example, on my Windows 2012 R2 server with WMF 5.1 and the same result.  DSC runs, detects that enabledprocotols in not in desired state, but doesn't update it

**Comment by virtrixke** [comment]
Same here. I'm using EnabledProtocols = @('net.tcp','net.pipe'). Only the first one is applied

**Comment by SpeedySquid** [comment]
I believe it is a string:
EnabledProtocols = "http,net.tcp"
This is working for me.

**Comment by Duffney** [comment]
When I attempted to use a single string I get the following error. I submitted a pull request that fixes this. There are two issues. 1.) it's looking for spaces not commas and 2.) it needs to replace the space with commas in the resource see pull request for more details. https://github.com/PowerShell/xWebAdministration/pull/295

xWebAdministration\xWebApplication : At least one of the values 'http, net.tcp' is not supported or valid for property 'EnabledProtocols' on class 'xWebApplication'. Please specify only supported 
values: 
http, https, net.tcp, net.msmq, net.pipe.

**Comment by Zuldan** [comment]
@Duffney I just came across this exact issue and was about to send a pull request when I came across this issue. Doh!

I'm surprised the fix hasn't been merged yet.

**Comment by rsawer** [comment]
I have that issue too with following EnabledProtocols array:
EnabledProtocols = @('http','net.pipe')
it seems to be totally ignored

**Comment by rsawer** [comment]
are you planning to correct this issue or it will be left that way ?

**Comment by remcoeissing** [comment]
Seems that I fixed this as part of #319 . There was a unit test that failed an I changed it to `$EnabledProtocols -join ','`. So this should be in release 1.19.0.0.

However I noticed that the Get never returns the proper result. I've put that on my list and will create a pull request for this.

**Comment by rsawer** [comment]
thanks for feedback, can't wait for new release!

**Comment by remcoeissing** [comment]
@rsawer Version 1.19.0.0 was released on November 15th. So you should be able to set multiple protocols now.

**Comment by johlju** [comment]
Closing this as resolved as per comments. Please reopen if that is not the case.
