### ISSUE TITLE
xWebAppPool: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported."

### ISSUE THREAD

**Issue by agarstang** [PowerShell/xWebAdministration#303]
I get the below error when using module version `1.17.0.0` on Windows Server 2016.

`Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported."`

Resource: **xWebAppPool**
Module Version: `1.17.0.0`
PowerShell Version: `5.1.14393.953`
IIS: `10.0.14393.0`
Windows 2016 Version 1607 Build 14393.953

When commenting out [this line](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L913) it works. I believe the casting of the AppCmd output needs better handling.

**Comment by Sjark** [comment]
I just ran into the same issue with 1.17.0.0. on Windows Server 2012 R2.

**Comment by agarstang** [comment]
@Sjark It was exactly the same thing for me :) - as long as you're not getting an error it shouldn't be a problem however it's not very useful in it's current form as it then suppresses the _**real**_ error message.

**Comment by tysonjhayes** [comment]
Unfortunately I'm not in a good place to repo this.  Could someone change the line to the following, and let me know if it fixes the problem?

````powershell
Write-Verbose -Message $($appcmdResult).ToString()
````

**Comment by agarstang** [comment]
@tysonjhayes this achieves the same result and I think casting at output rather than when storing the result is better idea. I have update #304 :)
