### ISSUE TITLE
CIM Class does not resolve correctly when specifying DSC resources in Import-DSCResource

### ISSUE THREAD

**Issue by mlanderos** [PowerShell/xWebAdministration#306]
Hi,

I am not sure if this is an issue or not as this is my first time reporting anything, so my apologies upfront if I a reporting something incorrectly. If there is a document on how to correctly report issues, please send the link my way.

Anyhow, in my example below the CIM class "MSFT_xWebAuthenticationInformation" does not resolve correctly if I specify the name of individual DSC resource(s) I am importing. This does not allow me to generate a .mof file. If I remove the individual name(s) then the CIM class works correctly and I am able to successfully create a .mof file. 

`
Configuration Test {

    Import-DscResource -ModuleName @{ModuleName="xWebAdministration";ModuleVersion="1.17.0.0"} -Name xWebsite

    Node localhost {

        xWebsite MainHTTPWebsite  
        {  
            Ensure          = "Present"  
            Name            = "Test"
            ApplicationPool = "MainAppPool" 
            State           = "Started"  
            PhysicalPath    = "C:\path\to\files"  
            BindingInfo     = @(
                                @(MSFT_xWebBindingInformation
                                    {  
                                        Protocol              = "HTTP"
                                        Port                  =  80 
                                        HostName              = "www.domain.tld"
                                    }
                                );
                                @(MSFT_xWebBindingInformation
                                    {
                                        Protocol              = "HTTPS"
                                        Port                  = 443
                                        HostName              = "www.domain.tld"
                                    }
                                )
                              ) 
        }
    }  
}

Test -output "C:\Temp"
`

The error I receive is "PSDesiredStateConfiguration\Node : The term 'MSFT_xWebBindingInformation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Below I have removed the -name parameter which allows me to generate a .mof file. 

`
Configuration Test {
    Import-DscResource -ModuleName @{ModuleName="xWebAdministration";ModuleVersion="1.17.0.0"}

    Node localhost {

        xWebsite MainHTTPWebsite  
        {  
            Ensure          = "Present"  
            Name            = "Test"
            ApplicationPool = "MainAppPool" 
            State           = "Started"  
            PhysicalPath    = "C:\path\to\files"  
            BindingInfo     = @(
                                @(MSFT_xWebBindingInformation
                                    {  
                                        Protocol              = "HTTP"
                                        Port                  =  80 
                                        HostName              = "www.domain.tld"
                                    }
                                );
                                @(MSFT_xWebBindingInformation
                                    {
                                        Protocol              = "HTTPS"
                                        Port                  = 443
                                        HostName              = "www.domain.tld"
                                    }
                                )
                              ) 
        }
    }  
}

Test -output "C:\Temp"`

My setup:
- 2012R2
- PS 5.0
-xWebAdministration 1.17.0.0

**Comment by johlju** [comment]
Sorry that nobody answered your question for so long. You did everything correct adding this issue.

I think this was a problem in how Import-DscResource was loading resource when using `-Name`. 🤔 I have seen it reported before in other resource modules. I think it resolved now in newer builds? I know this has nothing to with this resource module. But do you still have a problem with this, let me know. 

I'm closing this for now as it is an external issue.
