### ISSUE TITLE
xWebAdministration and ApplicationHost.config

### ISSUE THREAD

**Issue by virtrixke** [PowerShell/xWebAdministration#310]
We have an IIS with 30+ apppools and 30+website/webapps hosting WCF services.
When I run a DSC config for this server it results in sporadic errors and afterwards a number of settings are missing in the ApplicationHost.config.

Run the DSC again (and again) and every time some more settings are applied until it applies them all.
I'm under the impression that IIS/DSC can't handle the number of applicationHost.config changes.
The host system is Windows 2012 R2 with latest patches.

is this a known issue?

**Comment by johlju** [comment]
Sorry that nobody answered your issue for so long. Are you still seeing this issue? If so, what OS editon and version, WMF and if you have a configuration to reproduce this it would be great!
