### ISSUE TITLE
Group Managed Service Account

### ISSUE THREAD

**Issue by devbot920** [PowerShell/xWebAdministration#317]
I am attempting to configure IIS using a Group Managed Service Account.  I attempting using the configuration:
IdentityType = "SpecificUser"
Credential = $Cred
But I am getting an error stating:
The password supplied to the Desired State Configuration resource MSFT_xWebAppPool is not valid. The password cannot be null or empty.
    + CategoryInfo          : InvalidResult: (:) [], CimException
    + FullyQualifiedErrorId : InvalidPassword

The standard powershell to do this is:
Import-Module WebAdministration
$pool = Get-Item IIS:\AppPools\DefaultAppPool
$pool.processModel.identityType = 3
$pool.processModel.userName = "$env:USERDOMAIN\$gMSA_Name$"
$pool.processModel.password = ''
$pool | Set-Item

Can you provide any insight into this issue?

Thanks

**Comment by Hossman58** [comment]
How are you creating the _$Cred_ variable?

**Comment by johlju** [comment]
Lets track this problem in issue https://github.com/PowerShell/xWebAdministration/issues/80. Closing this issue.
