### ISSUE TITLE
Please Add support for DoAppIntAfterRestart 

### ISSUE THREAD

**Issue by Hossman58** [PowerShell/xWebAdministration#318]
Currently I have to run a separate PS script to make sure this is set on all of our PROD websites, but it would be nice to be able to set this in xWebsite and xWebApplication:

<code>
Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -location 'Default Web Site' -filter "system.webServer/applicationInitialization" -name "doAppInitAfterRestart" -value "True"
</code>

**Comment by regedit32** [comment]
This can be set with xWebConfigProperty, so this is now resolved by PR #330.  Please re-open if you feel this needs to be further addressed.
