### ISSUE TITLE
Stopped Default web site starts after reboot

### ISSUE THREAD

**Issue by mivica** [PowerShell/xWebAdministration#325]
Hi, I am using the below resource to ensure default web site is stopped on Win 2012 R2 server. It works fine initially, but after reboot, I am finding default website started and running making DSC configuration not complaint. I tried several combinations but they all work the same. Any ideas anyone?

xWebsite StopDefaultWebSite { 
	Name = "Default Web Site"; Ensure = "Present"; State = "Stopped";
	ServiceAutoStartEnabled = $false; PreloadEnabled = $false; PhysicalPath = "C:\inetpub\wwwroot"
	PsDscRunAsCredential = $AdminCred; DependsOn = "[WindowsFeature]WebServer"
}

**Comment by bozho** [comment]
To prevent website autostart, site's property ServerAutoStart needs to be set to $false, which xWebsite currently does not support.

I plan to submit a PR with the fix soon.

**Comment by johlju** [comment]
This is being worked on in PR #339
