### ISSUE TITLE
Question: Enable IIS for sharepoint installation

### ISSUE THREAD

**Issue by rsganta** [PowerShell/xWebAdministration#327]
I am trying to enable IIS logging for sharepoint product on a VM.  

Any examples for xIISModule of DSC ?

**Comment by remcoeissing** [comment]
I don't think you are looking for an example of xIISModule, instead you probably want examples of xIISLogging.

Examples:
- Logging rollover: https://github.com/PowerShell/xWebAdministration/blob/dev/Examples/Sample_xIisLogging_Rollover.ps1
- Truncate logs: https://github.com/PowerShell/xWebAdministration/blob/dev/Examples/Sample_xIisLogging_Truncate.ps1

Not sure what you want to log, but we have documented all the properties of xIISLogging in the Readme.md file.

**Comment by rsganta** [comment]
thanks @remcoeissing . Hope we can use both log period and log truncate size in the same block.

xIisLogging IISLogging

        {

            LogPath = $ConfigurationData.NonNodeData.IISLogpath
            Logflags = @('Date','Time','ClientIP','UserName','ServerIP')
            LoglocalTimeRollover = $true
            LogPeriod = 'Hourly'
            LogTruncateSize = '2097152'
            LogFormat = 'W3C'

        }

**Comment by rsganta** [comment]
@remcoeissing , can we use both log period and log truncate size in the same block?
