### ISSUE TITLE
Disable Debugging for ASP.NET Applications

### ISSUE THREAD

**Issue by bulentozkir** [PowerShell/xWebAdministration#328]
Is there any example for setting debug value to false using this module? 

https://support.microsoft.com/en-us/help/815157/how-to-disable-debugging-for-asp-net-applications

**Comment by onurbiyik** [comment]
I think it can be done via xWebConfigKeyValue. Just pass in "compilation" and "debug" as parameters.

**Comment by johlju** [comment]
@bulentozkir Were you able to resolve this with a available resource?
