### ISSUE TITLE
Refactor xIisHandler to eliminate the need for hard coding handler data

### ISSUE THREAD

**Issue by nehrua** [PowerShell/xWebAdministration#337]
Please reference the proposed schema below.  The idea is to allow the new resource to accept parameterized input that will be leveraged to create web handlers that include those hard coded in the current resource, as well as those not hard coded.  I'm working on this update, but wanted to get feedback on the proposed schema.

```powershell
[ClassVersion("1.0.0")]
class HandlerObject
{
  [Required, Description('Specifies the physical path to the handler')] string Path;
  [Required, Description('Specifies the HTTP verbs that are handled by the new handler'), ValueMap{'GET','HEAD','POST','DEBUG'}, Values{'GET','HEAD','POST','DEBUG'}] string Verb[];
  [Write, Description('Specifies the location for which the cmdlet returns handler information')] string Location;
  [Write, Description('Specifies the modules used for the handler')] string Modules;
  [Write, Description('Specifies preconditions for the new handler')] string PreCondition;
  [Write, Description('Specifies the user rights that are required for the new handler'), ValueMap{'Execute','None','Read','Write'}, Values{'Execute','None','Read','Write'}] string RequiredAccess;
  [Write, Description('Specifies the resource type this handler runs')] string ResourceType;
  [Write, Description('Specifies in MB the ASP response buffer limit')] uint32 ResponseBufferLimit;
  [Write, Description('Specifies the script processor that runs for the module')] string ScriptProcessor;
  [Write, Description('Specifies the managed type of the new module')] string Type;
  [Write, Description('Specifies whether the handler processes full path information in a URI')] boolean AllowPathInfo;
};

[ClassVersion("1.0.0"), FriendlyName("xIisHandler")] 
class MSFT_xIisHandler : OMI_BaseResource
{
  [Key, Description('Specifies the name of the new request handler')] string Name;
  [Required, Description('Specifies whether the handler will be installed on the system'), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
  [Read, Description('The handler object properties'), EmbeddedInstance('HandlerObject')] string HandlerObject[]
}
```

**Comment by johlju** [comment]
Looks very promising!

Only thing I can see directly is 
 * `HandlerObject` probably should be named `xWebApplicationHandlerInformation`, or just `xWebApplicationHandler`. 
* `Ensure` could default to `$true` and then it doesn't need to be `Required`, but `Write`.
* Property `HandlerObject` should probably be renamed to `Handler` (singular, it can be one or more), and it should have the type qualifier `Write`?

Labeling this as a breaking change, and help wanted. Let me know if you are working on this, then a label this as 'in progress'.

**Comment by johlju** [comment]
@boscoedash the change you are proposing in https://github.com/PowerShell/xWebAdministration/pull/360 will add a new resource for this instead? Will your proposal deprecate the resource xIisHandler?

**Comment by johlju** [comment]
@nehrua Can you see if the resource proposed in PR #360 works as you intended (with the exceptions that it's a new resource).

**Comment by nehrua** [comment]
@johlju The resource proposed in PR #360 works and I intended.  I worked with boscoedash and contributed to its development.  The resource in #360 is intended to deprecate xIisHandler, as it should be able to handle handlers hardcoded in the xIisHandler as well as many others.  Sorry for the confusion.

**Comment by johlju** [comment]
@nehrua No worries! Great collaboration! 😃 Then we should deprecate xIisHandler in PR #360 as well.
