### ISSUE TITLE
Extend xWebConfigKeyValue Support

### ISSUE THREAD

**Issue by rhys-intelliflo** [PowerShell/xWebAdministration#344]
https://github.com/PowerShell/xWebAdministration/blob/d022234030fb71a5c1d293aac9a1ee1ccaeac867/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L98

Why is this configured to only allow 'AppSettings'?

Is it better to remove the validateset ?

**Comment by johlju** [comment]
I think you looking for the resource that are currently in PR #330? Would they solve your problem?

**Comment by rhys-intelliflo** [comment]
Looks like it

**Comment by rhys-intelliflo** [comment]
thanks @johlju

**Comment by johlju** [comment]
This issue will auto-close once the PR is merged.
