### ISSUE TITLE
xIisFeatureDelegation error:  Failure to get the results from the script in a hash table format.

### ISSUE THREAD

**Issue by els-bernalj** [PowerShell/xWebAdministration#352]
Configuration: 

```
configuration HandlerMappingOverride {
    Import-DscResource -ModuleName xWebAdministration
    # Ensure that the IpSecurity setting can be overwritten.
    xIisFeatureDelegation handlermapping_delegation {
        SectionName = "handlers"
        OverrideMode = "Allow"

        DependsOn = "[WindowsFeature]Web-Server_feature"
    }
}
```

When i run Get-DSCConfiguration on the node i get the following error:
```
Get-DscConfiguration : PowerShell DSC resource MSFT_ScriptResource  failed to execute Get-TargetResource functionality
with error message: Failure to get the results from the script in a hash table format.
At line:1 char:1
+ Get-DscConfiguration -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager)
   [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure,Get-DscConfiguration
```

If i run Test and Set it seems to work, but it fails every time when i run get. I have another configuration running with a different section and i receive the same error.

**Comment by johlju** [comment]
It seems it fails on a Script resource you have in your configuration 'Get-DscConfiguration : PowerShell DSC resource **MSFT_ScriptResource**'. Can you confirm that you have a Script resource in your configuration?

**Comment by els-bernalj** [comment]
Hello @johlju,

I do have some script resources but those finish without any errors. I'll run this again and paste the verbose output so that it'll have more information.

**Comment by els-bernalj** [comment]
My apologies. You're right, i read that wrong. Sorry about that.
