### ISSUE TITLE
xIisFeatureDelegation should support any path instead of hard-coding /system.webServer

### ISSUE THREAD

**Issue by regedit32** [PowerShell/xWebAdministration#358]
Currently xIisFeatureDelegation has a hardcoded Set-WebConfiguration `-Filter "/system.webServer/$SectionName"` which limits the ability to unlock sections under any other path like '/system.web'.  I propose we make the filter more dynamic so an admin can specify any path.  This would be a breaking change if we do not create a new resource for this.

Another addition could be to update the resource to support managing this at the server level or site level.  Currently the resource only supports this at the server level.  This can be managed by adding an optional parameter for `PsPath` and default to 'machine/webroot/apphost' if not specifed.

**Comment by johlju** [comment]
Sounds good to me, breaking changes are okay. Can you propose an updated schema.mof which implementing both these changes?

**Comment by regedit32** [comment]
Sure thing, here's my proposed schema.mof:
```
[ClassVersion("1.0.0"), FriendlyName("xIisFeatureDelegation")]
class MSFT_xIisFeatureDelegation : OMI_BaseResource
{
  [Key, Description("Specifies the configuration path. This can be either an IIS configuration path in the format computer machine/webroot/apphost, or the IIS module path in this format IIS:\sites\Default Web Site.")] String PsPath;
  [Key, Description("Specifies the IIS configuration section to lock or unlock.")] String ConfigSection;
  [Required, Description("Determines whether to lock or unlock the specified section "), ValueMap{"Allow", "Deny"}, Values{"Allow", "Deny"}] string OverrideMode;
};
```

And an example configuration:
```
configuration MSFT_xIISFeatureDelegation_AllowDelegation
{
    Import-DscResource -ModuleName xWebAdministration

    xIisFeatureDelegation AllowDelegation
    {
        PsPath = 'IIS:\Sites\Default Web Site'
        ConfigSection = '/system.web/httpCookies'
        OverrideMode = 'Allow'
    }
}
```

Would I need to increment the class version in the schema.mof?  I can start working on resolving this issue.

**Comment by johlju** [comment]
I'm out of my depth here so I trust your knowledge on this one. It looks good to me, though the `PsPath` probably should be just `Path` if it can be either of those you mention in the property description.

Please see this pull request (example), they are not the same as this issue proposes? 
https://github.com/PowerShell/xWebAdministration/pull/330/files#diff-3cd75e0e55920bc9ff7953cf2a9daa0c

**Comment by johlju** [comment]
You don't need to increment the version in the schema. I think it the version of the "schema type", not the version of the "resource". Never seen this change.

**Comment by regedit32** [comment]
Yes, the Filter and WebsitePath properties on that resource are essentially the same as the ones I called PsPath and ConfigSection.  I can use those names as instead, I think Filter especially would be more appropriate.

The two resources are different as one is managing web properties and this one is managing web elements, specifically the lock metadata.

**Comment by johlju** [comment]
Sounds good too me.
