### ISSUE TITLE
Readme.md is missing new resources added in version 1.7.0.0

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/xWebAdministration#38]
Missing the property descriptions for the following new resources added in 1.7.0.0
◦xIisHandler
◦xIisFeatureDelegation
◦xIisMimeTypeMapping
◦xWebAppPoolDefaults
◦xWebSiteDefaults

**Comment by tysonjhayes** [comment]
Currently see these in the README.MD so I'm closing this down.
