### ISSUE TITLE
WebAdministrationDsc property is AuthenticationInfo not AuthenticationInformation on Website

### ISSUE THREAD

**Issue by elduddz** [PowerShell/xWebAdministration#390]
Property on Website element as part of WebAdministrationDsc is documented in the readme as AuthenticationInformation, I get an error on running saying that AuthenticationInfo is supported not AuthenticationInformation.

**Comment by regedit32** [comment]
@elduddz hi, I'm not clear on the specifics of the issue or what resource it is in reference to.  Can you provide an example configuration to reproduce this error?

**Comment by elduddz** [comment]
On the webadministrationdsc branch there is a property defined for the website element as authenticationinformation this should be authenticationinfo

So the following errors

```
Website web {
Authenticationinformation = Msft_ etc
}
```

**Comment by johlju** [comment]
The WebAdministrationDsc branch haven’t been worked on for 2 years. It was WIP (Work In Progress) back then I wasn’t finished. The dev branch is the branch that should be used, and WebAdministrationDsc should probably be deleted because the dev branch has progress so much further, and it’s probably a lot of work resolving conflicts in that branch after two years. 

So please use the dev branch.

**Comment by johlju** [comment]
Please also note that the master branch is he branch currently released to PowerShell Gallery.

**Comment by elduddz** [comment]
Ok thanks, I'm getting everything from powershell gallery.

The master branch is xwebadmin I was using webadmindsc because I thought everything was going that way?

The link to the project from powershell gallery for webadmindsc brings you to the webadmindsc branch. So that is what I was following for the readme details.
________________________________

**Comment by johlju** [comment]
Aha, I didn’t know that branch was deployed to PowerShell Gallery, but as version 0.1.0.0, so looks like a test more than an actual release. Either way, that is less than good, since people are using two different modules. 

There haven’t been a release of

**Comment by elduddz** [comment]
👍 ok I'll revert back to xwebadmin I thought it was a bit odd to be using website but xwebapppool in the same DSC 😁
