### ISSUE TITLE
WebApplicationHandler: Does not allow 'Location' parameter usage for targeting virtual directories

### ISSUE THREAD

**Issue by boscoedash** [PowerShell/xWebAdministration#392]
#### Details of the scenario you tried and the problem that is occurring

- discussed in issue description

#### Suggested solution to the issue

- add location parameter

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

- anything that targets a virtual directory

**Comment by regedit32** [comment]
Fixed per #394
