### ISSUE TITLE
xWebAdministration: xWebSite: Impossible to set Site ID

### ISSUE THREAD

**Issue by Francois-Rousseau** [PowerShell/xWebAdministration#396]
#### Details of the scenario you tried and the problem that is occurring
There is no property to set the ID of a site while creating a WebSite with xWebSite ressource.

#### Suggested solution to the issue
Add a "ID" property in the ressource so we can specify the site ID.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
 'xWebAdministration' -ModuleVersion "2.0.0.0"

**Comment by johlju** [comment]
This looks like it would be an easier addition to the resource, passing the a `SiteId` as parameter and adding that ti the `Id` parameter on the cmdlet [New-WebSite](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-website).

*Maybe we should avoid using `Id` as a parameter on the resource as it might conflict with a built-in property in the future?*

**Comment by csharmath** [comment]
@johlju - do you mind taking a quick look at this commit ?
https://github.com/csharmath/xWebAdministration/commit/539e6ced13dad1ec6ee3f08b9e9c9e5dad205481
