### ISSUE TITLE
xWebConfigProperty Filter property showing Missing function body in function declaration.

### ISSUE THREAD

**Issue by sernone** [PowerShell/xWebAdministration#402]
#### Details of the scenario you tried and the problem that is occurring
 xWebConfigProperty "Web$($loc)Config" {
            Ensure = "Present"
            WebsitePath = "IIS:Default Web Site/$Using:loc"
            Filter = 'security/access'
            PropertyName = "sslflags"
            Value = "None"
        }

Missing function body in function declaration.

+             Filter = "//security/access"
+                     ~
Missing function body in function declaration.

https://github.com/PowerShell/xWebAdministration/issues/402#issue-370831293.

#### Verbose logs showing the problem

{
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "PowerShell54905ea8-f2ff-4d1e-b3fe-75e40e404068",
	"severity": 8,
	"message": "Missing function body in function declaration.",
	"source": "PowerShell",
	"startLineNumber": 104,
	"startColumn": 21,
	"endLineNumber": 104,
	"endColumn": 21
}

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
master

**Comment by regedit32** [comment]
Hello @sernone , can you provide more context to the configuration script you are using and when the error occurs?  Do you get this error when compiling the MOF or after the MOF is applied to the node?

You shouldn't need the `$using:` scope inside the resouce block.  You're also missing the `\` in the IIS path.  Maybe it was a bad copy/paste, but can you try this instead:

```powershell
    Node $NodeName
    {
        xWebConfigProperty "Web$($loc)Config"
        {
            Ensure       = "Present"
            WebsitePath  = "IIS:\Default Web Site\$loc"
            Filter       = "security/access"
            PropertyName = "sslflags"
            Value        = "None"
        }
    }
```

**Comment by janis-veinbergs** [comment]
This was happening to me too. The issue was this line: `Import-DscResource -ModuleName 'xWebAdministration' -Name 'xWebConfigProperty*'`

Changing to `Import-DscResource -ModuleName 'xWebAdministration' -Name 'xWebConfigProperty'` worked. (Removed the wildcard char)
