### ISSUE TITLE
Version on the PSGallery

### ISSUE THREAD

**Issue by SergeDubovsky** [PowerShell/xWebAdministration#404]
![image](https://user-images.githubusercontent.com/1774209/47568978-7458bc80-d900-11e8-849c-670ac5ccd69e.png)
A little trouble - our targets are not web-connected, so we host a local repository for resources, we need. Yesterday I had some troubles trying to use a direct copy of xWebAdministration, pushed to a local repo. On the PSGallery, the package version is 2.3.0 in the module it is 2.3.0.0, so when deployed, it was complaining about missing resources.
Is there a recipe, how to install this module from NuGet? 

Thank you.

**Comment by darkonejr** [comment]
Can confirm this is an issue with people who import this package into a local repo (like ProGet).   When I edit the .nuspec and change the version 2.3.0.0, everything works.  I'd submit a PR to fix, but the nuspec isn't in the git repo.

**Comment by darkonejr** [comment]
Bumping this, this is still an issue.

**Comment by darkonejr** [comment]
Another bump, this is still a problem for us.

**Comment by regedit32** [comment]
Is this still an issue after the latest 2.4.0.0 release?

**Comment by darkonejr** [comment]
Yes.  The nuspec has `2.4.0`, the .psd1 has `2.4.0.0`

**Comment by regedit32** [comment]
@darkonejr thanks for confirming.

**Comment by darkonejr** [comment]
Just a reminder here, this is still broken in 2.5.0.0

**Comment by johlju** [comment]
This is discussed here and will be resolved for all repos in the DSC Resource Kit when possible, so closing this issue.

**Comment by johlju** [comment]
Sorry, the issue https://github.com/PowerShell/DscResources/issues/508 is where this is being discussed. 🙂
