### ISSUE TITLE
xWebsite - Get-TargetResource returns LogFlags as a single element array instead of an array of strings

### ISSUE THREAD

**Issue by bswerdlen** [PowerShell/xWebAdministration#405]
#### Details of the scenario you tried and the problem that is occurring
When running the xWebsite function Get-TargetResource the LogFlags key of the hashtable of data returned contains a single string element of all log flags separated by a comma. Expected behavior is a multi-element array where each element contains 1 log flag.

### First, I copied all content of MSFT_xWebsite.psm1 into my current environment
PS> $resource = Get-TargetResource <SiteName>

# Visual representation of what is stored in LogFlags
PS> $resource.LogFlags
Date,Time,ClientIP,UserName,SiteName,ComputerName,ServerIP,Method,UriStem,UriQuery,HttpStatus,Win32Status,BytesSent,BytesRecv,TimeTaken,ServerPort,UserAgent,Referer,ProtocolVersion,Host,HttpSubStatus

# Measuring the object to verify LogFlags is only 1 element
PS> $resource.LogFlags| measure
Count    : 1
...

# Measure of how many elements should have been in LogFlags
PS> $resource.LogFlags.Split(',') | measure
Count    : 21
...

#### Suggested solution to the issue
In Get-TargetResource change the following line (163 as of v2.2.0.0):
LogFlags                 = [Array]$website.logfile.LogExtFileFlags

to
LogFlags                 = [Array]$website.logfile.LogExtFileFlags.Split(',')

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
None, this is a manually generated issue that would only be seen when calling Get-DscConfiguration

# insert configuration here
No configuration used, this happens for any website defined

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19153.amd64fre.winblue_ltsb.180908-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.2.0.0

**Comment by bswerdlen** [comment]
I have also stumbled on this being an issue with xIisLogging for the LogFlags parameter. The same fix is recommended

**Comment by regedit32** [comment]
I agree.  The LogExtFileFlags value returned from IIS is not an array, but since the resource was designed to accept an array for this setting, then we should be returning the value as an array. Your proposed solution would be a good enhancement.
