### ISSUE TITLE
xWebAdministration: nupkg includes .git .github .vscode etc

### ISSUE THREAD

**Issue by csharmath** [PowerShell/xWebAdministration#406]
#### Details of the scenario you tried and the problem that is occurring
@kwirkykat 
The xWebAdministration nupkg package ships with it's git repo.
Should be ignored for nuget packaging.

```
Save-Module -Name xWebAdministration -Path .\xWebAdministration
> cd .\xWebAdministration\2.3.0.0\
[master ≡ +1 ~0 -3 !] ...nistration\xWebAdministration\2.3.0.0
> git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    .gitattributes
        deleted:    .gitignore
        deleted:    appveyor.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        PSGetModuleInfo.xml

no changes added to commit (use "git add" and/or "git commit -a")
[master ≡ +1 ~0 -3 !] ...nistration\xWebAdministration\2.3.0.0
> git log -1
commit fdefca3d031b26bbc71333e7305713a6721a8cde
Merge: e273b8b b8f7441
Author: Katie Keim <kwirkykat@users.noreply.github.com>
Date:   Wed Oct 24 17:22:02 2018 -0700

    Merge pull request #403 from PowerShell/dev

    Release of version 2.3.0.0 of xWebAdministration
[master ≡ +1 ~0 -3 !] ...nistration\xWebAdministration\2.3.0.0
```
#### Verbose logs showing the problem
see above
#### Suggested solution to the issue
ignore git
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
not relevant
#### The operating system the target node is running
not relevant

#### Version and build of PowerShell the target node is running
not relevant

#### Version of the DSC module that was used ('dev' if using current dev branch)

xWebAdministration 2.3.0.0

**Comment by csharmath** [comment]
bump

**Comment by rkyttle** [comment]
I ran into an issue with this as well.  Working with DSC and Azure, and I was trying to commit this module inside of my own Git repo which is setup to auto build zip files needed for Azure to work with DSC and I was unable to commit the module files until I removed all of the unneeded <.> folders/files

**Comment by csharmath** [comment]
Hello @kwirkykat, 

don't mean to bug you but you seem to be the maintainer of this module.
It seems like that this is a packaging / publishing issue impacting other DSC modules as well for example the Azure one mentioned by @rkyttle or xExchange just to mention a few more.

And it's not uncommon that folks are saving a module then trying to git commit to their own repos to track it as a 3rd party which is now broken for a couple of DSC modules.

Even if this issue should not belong to you, do you mind just passing it along to the right folks who can review the module publishing for DSC and clean it up to remove .git .vscode etc ?

It can also double the size of the module in some cases, depends on the git history size.

Thank you!

**Comment by regedit32** [comment]
The .git files have now been removed as of the current release 2.4.0.0
