### ISSUE TITLE
MSFT_xIisLogging.psm1 does not contain a parameter for $TargetLogW3C

### ISSUE THREAD

**Issue by erjenkin** [PowerShell/xWebAdministration#414]
#### Details of the scenario you tried and the problem that is occurring
MSFT_xIisLogging.psm1 does not contain a parameter for $TargetLogW3C with ValidSet('File', 'ETW', 'File,ETW'). This configuration item is required to maintain compliance with security guidelines for IIS server (STIG V-76683)
#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/44269812/52302222-7c41e700-295a-11e9-9c9d-60c0a332a9d2.png)
#### Suggested solution to the issue
Add parameter to MSFT_xIisLogging.psm1
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
#### The operating system the target node is running

#### Version and build of PowerShell the target node is running

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by regedit32** [comment]
@erjenkin Thanks for opening the issue.  This will be a good enhancement to the resource.
