### ISSUE TITLE
Help wanted. xWebConfigPropertyCollection

### ISSUE THREAD

**Issue by danSpotter** [PowerShell/xWebAdministration#420]
I have a script I'm converting to DSC that has 50 some iterations of set-webconfigurationproperty. Can these be combined? Is this what xWebConfigPropertyCollection is used for?

Set-WebConfigurationProperty "/system.applicationHost/applicationPools/applicationPoolDefaults/processModel" -Name "idleTimeout" -Value 00:20:00
		
Set-WebConfigurationProperty "/system.applicationHost/applicationPools/applicationPoolDefaults/processModel" -Name "pingingEnabled" -Value "$True"
		
Set-WebConfigurationProperty "/system.applicationHost/applicationPools/applicationPoolDefaults/failure" -Name "rapidFailProtection" -Value "$True"
		
Set-WebConfigurationProperty "/system.applicationHost/applicationPools/applicationPoolDefaults/failure" -Name "rapidFailProtectionInterval" -Value 00:05:00

**Comment by johlju** [comment]
I think `xWebConfigPropertyCollection` is meant to configure a value for an array (collection) of values. 🤔 Maybe you are looking for `xWebConfigProperty`? You must add each value as a separate instance I think.

See examples here; https://github.com/PowerShell/xWebAdministration/tree/dev/Examples

If you have solved you issue and have an examples that you can share then please send in an pull request to update/add examples.

You can also try asking your question on the Slack channel https://dsccommunity.org/community/contact/

Closing this issue at this time.
