### ISSUE TITLE
xWebConfigKeyValue use of Key values in schema

### ISSUE THREAD

**Issue by leshkinski** [PowerShell/xWebAdministration#44]
I think that it would make sense to remove 'key' attribute for ['ConfigSection' and 'WebsitePath'](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.schema.mof#L5-L6) properties to allow for multiple invocation of xWebConfigKeyValue resource against the same site or configuration section. 

Leaving just the 'Key' property as the only one with 'key' attribute set would cater for situation where a user needs to add multiple Key/Value entries within the same configuration section and/or for the same site. An example of this is adding multiple custom script handler mappings for the same site/root instance.

If a particular property is mandatory then setting a sensible/safe default value may be a better approach, which would remove the multiple 'key' attribute requirement.

**Comment by tysonjhayes** [comment]
Completely agree, would you want to submit a PR for this? I think we'd want to get some baseline testing in for the resource which could just be calling in Test-xDscResource/Test-xDscSchema so if you wanted to submit that change and include the pester tests we could get that pulled in.

**Comment by TravisEz13** [comment]
Does the same key mean the same value across different sites?  
Does the same key mean the same value across different sections in the same site?

if not, these values should probably remain part of the key.

**Comment by leshkinski** [comment]
@tysonjhayes as soon as I have some time to do this, I will :)

@TravisEz13 the issue is that this limits use of this resource within a foreach loop to add multiple sets of entries under the same site/server section. An example of this would be attempting to create a set of request handler mappings by defining an array or hashtable with desired values and then looping through them with this resource - the moment you do this, you will get duplicate key values. I ended up writing a Script resource to handle this, but would have been so much easier if the only key was the 'Key', as this would be the only unique property.

**Comment by TravisEz13** [comment]
Can you give a code example of how the current key structure would lead to duplicate keys.  It seems to me if the proposed key would be unique then the current key would be unique as well since the proposed key is a subset of the current key.

**Comment by leshkinski** [comment]
Sure, other than my earlier comment, this discussion demonstrates the issue perfectly: http://stackoverflow.com/questions/26715911/how-do-i-set-multiple-appsettings-values-using-xwebconfigkeyvalue

In my specific case, I was deploying a customer application and wanted to use a foreach loop, within which I planned to deploy configuration of 10 additional web handlers. Because all ten unique key properties referenced the same section and path. This module was unsuitable due to the 'ConfigSection' and 'WebsitePath' properties having the 'key' attribute set against them, meaning that they could not be used multiple times within the same configuration block. This limitation was in addition to the existing issue #42 

My solution was to use a Script Resource due to time constraints:

        $isapiMappings = @("addr",
                            "htm",
                            "chkout",
                            "health",
                            "ajax",
                            "falcon",
                            "srch",
                            "axd",
                            "provider",
                            "ipn",
                            "smartpay"
                         )
        
        Script IISHandlers
        {
            GetScript = {
                return @{
                            mappings = $($using:isapiMappings)
                        }
            }
            SetScript = {
                foreach ($handlerName in $using:isapiMappings)
                {
                    if ([bool](Get-WebHandler -Name $handlerName))
                    {
                        Set-WebHandler -Name $handlerName `
                                       -Path "*.$handlerName" `
                                       -Verb "*" `
                                       -Modules "IsapiModule" `
                                       -RequiredAccess Script `
                                       -ScriptProcessor "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll"
                    }
                    else
                    {
                        New-WebHandler -Name $handlerName `
                                       -Path "*.$handlerName" `
                                       -Verb "*" `
                                       -Modules "IsapiModule" `
                                       -RequiredAccess Script `
                                       -ScriptProcessor "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll"
                    }
                }
            }
            TestScript = {
                foreach ($handlerName in $using:isapiMappings)
                {
                    $current = Get-WebHandler -Name $handlerName | Select-Object name,path,verb,modules,scriptProcessor,requireaccess
                
                    if (($current.name -ne $handlerName) -or ($current.path -ne "*.$handlerName") -or
                        ($current.modules -ne "IsapiModule") -or ($current.requireAccess -ne "Script") -or
                        ($current.scriptProcessor -ne "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll") -or
                        ($current.verb -ne "`*") )
                        {
                            Write-Verbose "Test for $handlerName handler has failed"
                            Return $false
                        }
                }
                Return $True
            }
            DependsOn = @("[WindowsFeature]IIS")
        }

This is definitely a bit of a hack, so don't judge too much - desperate times call for desperate measures :)

**Comment by TravisEz13** [comment]
@leshkinski @tysonjhayes I believe I understand the problem, but the suggested solutions goes in the wrong direction.  Removing keys will allow fewer resources to be specified.  I believe the correct solution is to change the property key from required to a key. 

Which already done in [this commit](https://github.com/PowerShell/xWebAdministration/commit/45b92522d78b78743970d629c72fb13e2d4a8d7d)

**Comment by rosberglinhares** [comment]
This issue was already fixed by the commit said by @TravisEz13. Shouldn't it be closed?

**Comment by johlju** [comment]
I'm closing this issue as resolved. Please reopen or comment if this isn't true.
