### ISSUE TITLE
Move change log from README.md to CHANGELOG.md 

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#446]
We should move the change log out from the README.md and into a separate file CHANGELOG.md.

See example https://github.com/PowerShell/ActiveDirectoryDsc/blob/dev/CHANGELOG.md

Also in the README.md we should add a change log section. See example https://github.com/PowerShell/ActiveDirectoryDsc#change-log

**Comment by devevignesh** [comment]
I would like to claim this. Thanks

**Comment by johlju** [comment]
@devevignesh it's yours, looking forward to the PR! 😄

**Comment by johlju** [comment]
We must also update the first entry in the file https://github.com/PowerShell/xWebAdministration/blob/dev/.github/PULL_REQUEST_TEMPLATE.md. It should say that we should update the Unreleased section in CHANGELOG.md.

**Comment by devevignesh** [comment]
@johlju Opened PR for your review. Thanks.
