### ISSUE TITLE
Optimize the exporting in the module manifest

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#448]
See https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/powershell/module-authoring-considerations

We should change 

https://github.com/PowerShell/xWebAdministration/blob/4f19e762c648af0346b6fef382bf5e1c674a48dd/xWebAdministration.psd1#L61-L65

To

```powershell
  # Functions to export from this module
  FunctionsToExport = @()

  # Cmdlets to export from this module
  CmdletsToExport = @()

  # Variables to export from this module
  VariablesToExport = @()

  # Aliases to export from this module
  AliasesToExport = @()
```

**Comment by zufishanali** [comment]
Hi @johlju , I would like to work on this issue. 

Thanks, 
Zufishan
