### ISSUE TITLE
Add a a ToC to the resource section in the README.md

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#450]
We should add a ToC to the top of the resource section in the README.md, before all the individual resource sections. The Table of Contents should look similar to this example https://github.com/PowerShell/SqlServerDsc#resources. The Table of Contents should be in alphabetical order and have a link to each individual resource section.

This should replace the list at the top a line 3 https://github.com/PowerShell/xWebAdministration/blame/dev/README.md#L3

**Comment by midacts** [comment]
Dibs

**Comment by johlju** [comment]
First part of yhis issue is done, I forgot when I reviewed that we needed to remove the incomplete list on line 3 as well. 

@midacts Would you mind sending in another PR that removes the list of resource on line 3? 

This is open again for anyone in the community. 🙂
