### ISSUE TITLE
xWebAppPoolDefaults: Should be made to follow the best practice for single instance resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#462]
The resource should be changed to follow the best practices to make single instance resource. This would change the property name of the key property. This is a breaking change.

https://docs.microsoft.com/en-us/powershell/dsc/resources/singleinstance

**Comment by RandomNoun7** [comment]
@johlju I just got test suite to run successfully to make sure I can update the tests properly. I would like to start working on this and the other issue of this type within the next few days.

**Comment by johlju** [comment]
Labeled this in progress, as well as the issue https://github.com/PowerShell/xWebAdministration/issues/457. Let me know if you need anything. 🙂
