### ISSUE TITLE
xWebSiteDefaults: Move localization strings to strings.psd1 file

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#476]
We should move the localization strings to a strings.psd1 file. See the localization https://dsccommunity.org/guidelines/localization/

**Comment by hacky1997** [comment]
where is the strings.psd1? can u please tell me?

**Comment by hacky1997** [comment]
Is this open till now? please tell me

**Comment by johlju** [comment]
I'm sorry, I don't understand what you mean. Could you try to rephrase your question? 🙂

**Comment by hacky1997** [comment]
I just asked that anybody has send you a pull request regarding this issue? If not then can you tell me which strings.psd1 I have to moved? Because there are lots of strings.psd1

**Comment by hacky1997** [comment]
Ok!! I understand everything. :) I have to replace that code into strings.psd1 right?

**Comment by johlju** [comment]
Not yet what I know of. I will label this as in progress if you want to work on it.

Please see this other DSC resource how it should looks like.
https://github.com/PowerShell/xWebAdministration/tree/dev/DSCResources/MSFT_WebApplicationHandler

You need to create a new `en-US` folder with a correct name of the strings.psd; `MSFT_xWebSiteDefaults.strings.psd1`. 

Then you need to add this to the resource code (the helper function will load the correct localized string)

https://github.com/PowerShell/xWebAdministration/blob/4dab473e5244c35c17786305dee3d55bcf26627b/DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.psm1#L7-L8

**Comment by hacky1997** [comment]
Just add this two line?
# Import Localization Strings 
 $script:localizedData = Get-LocalizedData -ResourceName 'MSFT_WebApplicationHandler'

**Comment by hacky1997** [comment]
Just send the pull request :)
