### ISSUE TITLE
xWebAdministration tests fail on local machine cause module isn't deployed

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/xWebAdministration#48]
xWebAdministration tests fail cause they expect the module to be deployed on a machine.
Tests are passing on appveyor builds because in appveyor.yml we modify PSModulePath so that development version is discovered:
```
$tempModulePath = (Resolve-Path (join-path $PWD '..')).ProviderPath 
$env:PSModulePath = "$env:PSModulePath;$tempModulePath 
```

We should be deploying the module during the test execution instead (similarily to: https://github.com/PowerShell/xTimeZone/pull/12/files ) so that we can run tests successfully on local machine as well.

**Comment by tysonjhayes** [comment]
Do we want to remove the appvoyer part where we modify the PSModulePath? If we're copying the files around there doesn't seem to be a need for the modification.
