### ISSUE TITLE
Update change log task list entry in PULL_REQUEST_TEMPLATE.md 

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#481]
I suggest to change the chnage log task list entry to the following. Helping contributors to understand what the change log entry should consist of.

```
- [ ] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
```

**Comment by Sweta271097** [comment]
@johlju Can I take up this issue?

**Comment by Sweta271097** [comment]
@johlju For this task are we supposed to create changes in the Readme.md or create a new CHANGELOG.md?

**Comment by johlju** [comment]
Ah my bad. Forgot to mention that this PR https://github.com/PowerShell/xWebAdministration/pull/480 is moving the change log from the README.md. So I created this issue to get an updated text in the PULL_REQUEST_TEMPLATE.md.

You only need to update the entry in the PULL_REQUEST_TEMPLATE.md, but you will probably have to resolve conflicts after I have merged the above PR, or wait until the above PR is merged.

**Comment by johlju** [comment]
@Sweta271097 you may have this issue. 😃

**Comment by Sweta271097** [comment]
@johlju Thanks, I'm on it.

**Comment by johlju** [comment]
PR #480 is merged now! So go ahead and send in this whenever you have time.

**Comment by johlju** [comment]
I had to resolve this to help contributors add the correct entry to the change log. This was merged in a recent PR.
