### ISSUE TITLE
xWebSite: Move example from README.md to examples folder

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#487]
This example https://github.com/PowerShell/xWebAdministration#create-a-new-website should be added as new example, and in the description for the comment-based help it should use the text that describing the example in the README.md.

**Comment by tomlarse** [comment]
There already is a `Sample_xWebsite_NewWebsite.ps1` in the `/Resources/xWebsite/` folder, and there are really two configuration examples in the readme. I think the difference between the existing one and the first one from readme is only that the example in readme is configuring an HTTPS site.  The second example in the readme is with a hostname for when the certificate being generated in the same configuration. Should we split them into more files maybe?

- `Sample_xWebsite_NewWebsiteHttps.ps1`
- `Sample_xWebsite_NewWebsiteCertreq.ps1`

Or something like that?

**Comment by johlju** [comment]
This is being worked on in PR https://github.com/PowerShell/xWebAdministration/pull/490
