### ISSUE TITLE
xWebAppPool: Remove example from README.md

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#489]
We should remove this example from README.md https://github.com/PowerShell/xWebAdministration#create-and-configure-an-application-pool since there already is an example in the Examples folder that covers this.

**Comment by Abijith10** [comment]
Should I remove the last example alone?

**Comment by johlju** [comment]
Remove the entire section `create-and-configure-an-application-pool`. The other examples should be moved.

**Comment by Abijith10** [comment]
Ok I am on it.

**Comment by Abijith10** [comment]
Done and did a pull request. :)

**Comment by johlju** [comment]
This is open for any contributor again since there are currently no PR open to resolve this.
