### ISSUE TITLE
xWebAdministration: Move example from README.md to examples folder

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#491]
This example https://github.com/PowerShell/xWebAdministration#all-resources-end-to-end-scenario should be moved to the Examples folder. Preferably in the root of the Examples folder as an end-to-end example. In the description for the comment-based help it should use the text that describing the example in the README.md.

The configuration `Sample_IISServerDefaults` should be incorporated into the end-to-end example as best it can be. If it is not possible, then just remove it as they have individual resource examples already too.

*Please note that examples are tested so they can be compiled.*

**Comment by Abijith10** [comment]
What do I name the file?

**Comment by johlju** [comment]
I suggest `Sample_AllResources_EndToEnd.ps1`

Also, please see this example how to add a comment-based block for the descriptive text that is in the README.md.

https://github.com/PowerShell/ActiveDirectoryDsc/blob/dev/Examples/Resources/ADComputer/1-ADComputer_AddComputerAccount_Config.ps1#L20-L24

**Comment by Abijith10** [comment]
This is the description of Readme.md? I'm a bit slow on understanding it.

**Comment by johlju** [comment]
Oh my bad, there was no descriptive text in the README.md. Just add the description `End to end sample for xWebAdministration` to the comment-based help.

**Comment by johlju** [comment]
This is still up for grabs. 

/cc @tomlarse
