### ISSUE TITLE
xWebAdministration tests are failing

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/xWebAdministration#52]
see https://github.com/PowerShell/xWebAdministration/pull/51

**Comment by KarolKaczmarek** [comment]
Hi @TravisEz13 ,
We are seeing many test failures in this module recently. 
This is blocking acceptance of the outstanding PRs and new releases. 
Could you please take a look at this?

**Comment by tysonjhayes** [comment]
Is it possible this is related to the change I made in xDSCResources (https://github.com/PowerShell/xDSCResourceDesigner/pull/29) if so would publishing the fix so we can pull down the newer version actually fix the issue?

**Comment by KarolKaczmarek** [comment]
After publishing xDSCResourceDesigner, we are still seeing these errors: https://ci.appveyor.com/project/PowerShell/xwebadministration/build/1.0.140

**Comment by KarolKaczmarek** [comment]
```
[-] Error occurred in test script 'C:\projects\xwebadministration\Tests\Integration\MSFT_xIISServerLevelIntegration.Tests.ps1' 9.91s
  At C:\projects\xwebadministration\Tests\Integration\MSFT_xIISServerLevelIntegration.Tests.ps1:70 char:17
  +                 Import-DscResource -ModuleName xWebAdministration
  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Multiple versions of the module 'xWebAdministration' were found. You can run 'Get-DscResource -Module xWebAdministration' to see available versions on the system, and then use the fully qualified name in the following command to specify the desired version: 'Import-Module –ModuleName @{ModuleName=xWebAdministration;ModuleVersion=Version}'.
  
  At C:\projects\xwebadministration\Tests\Integration\MSFT_xIISServerLevelIntegration.Tests.ps1:94 char:17
  +                 Import-DscResource -ModuleName xWebAdministration
  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tysonjhayes** [comment]
Well at least it's a slightly different error? :grin:

**Comment by KarolKaczmarek** [comment]
Actually, that's the one I've seen when opening this issue. There were some new issues introduced in the meantime which seem to be resolved with the XDscResourceDesigner update, but the original issue is still there. 

The error indicates we have xWebAdministration deployed twice.. 

according to appveyor.yml, one is:
```
$tempModulePath = (Resolve-Path (join-path $PWD '..')).ProviderPath 
$env:PSModulePath = "$env:PSModulePath;$tempModulePath" 
```

aware of any other place we may be deploying it/adding to PSModulePath?

**Comment by tysonjhayes** [comment]
This has been fixed up and all tests have been passing that have been submitted (that don't actually have something wrong with them. :grin: )
