### ISSUE TITLE
xSslSettings: Resolve casing in name

### ISSUE THREAD

**Issue by johlju** [PowerShell/xWebAdministration#536]
There are files and folders that are named `xSSLSettings` instead of `xSslSettings`(lower-case 'sl'). Also code referencing `xSSLSettings` should be changed to `xSslSettings`.

**Comment by RandomNoun7** [comment]
@johlju It seems likely the person who did #504 may have thought they fixed the file and folder names previously. Unfortunately, fixing the case of folders and files like this on a Windows system is very difficult. The only practical way to do it is as I did, which is the clone the repository down to a Linux system that has a case sensitive file system, and use `git mv -f` to get the file moves done in a way that git will retain in a commit.

I hope this is what you're looking for here.

**Comment by johlju** [comment]
Is is possible to do it on Windows to by renaming (using `git mv`) the folder and files to something else and then back to the correct name. 

I missed the problem in the files and folders when reviewing the previous PR. But I think that PR solved all the code changes. 😊

**Comment by johlju** [comment]
Thank you for the PR :smile:

**Comment by RandomNoun7** [comment]
It should be possible in theory, but it doesn't quite work. Git always gets confused about which files are being moved around. Maybe if you did the moves in a really granular way committing each move as you did them you could get it done. But it's much easier to just spin up an ubunutu container and move them directly :)

**Comment by johlju** [comment]
Agree it is faster in Linux. So rarely I done it, just a file here and there, so I did the granular approach of renaming. :)
