### ISSUE TITLE
Powershell.org resources

### ISSUE THREAD

**Issue by ghost** [PowerShell/xWebAdministration#6]
Have you guys looked at these? https://github.com/PowerShellOrg/cWebAdministration/tree/master/DSCResources 

There are a bunch of enhancements and fixes, especially on the app pool side.  It may be beneficial to move some of those changes over here.

**Comment by vors** [comment]
Yes, there is finally no need to have "x" and "c" resources separately. We can take contributions from community back to "x" resources, and we definitely want to merge them. It would be awesome if somebody from community will work on pull request for that, it would speed up the process significantly.

**Comment by zuehlaa** [comment]
Would you prefer many smaller PRs that only deal with a new feature or bug fix, or would you just like to have the "c" and "x" merged together, tested, and 1 big PR?  I'm more than willing to help where I can.

**Comment by vors** [comment]
It's a good question. One time 1 big PR with significant testing would be easier for your and fine for us. For all future development, we would prefer to deal with small PRs, scoping one particular aspect.

**Comment by zuehlaa** [comment]
Sounds good.  I'll start looking at the website and app pool modules

**Comment by mbreakey3** [comment]
Should this issue be closed?
