### ISSUE TITLE
Why is xWebConfigKeyValue Limited to AppSettings?

### ISSUE THREAD

**Issue by craig-martin** [PowerShell/xWebAdministration#60]
Seems like a big restriction, wondering why this resource isn't able to act on more paths.  I would like to use it to set the authentication options for example (disable/enable anonymous).

**Comment by tysonjhayes** [comment]
I'd thought I'd filed an issue on this previously but I can't find it, :+1: from me.

**Comment by tysonjhayes** [comment]
Actually this is a dupe of #42 (more or less). So I'm going to close this one.
