### ISSUE TITLE
Issue creating site

### ISSUE THREAD

**Issue by josemaparicio** [PowerShell/xWebAdministration#62]
Hi,

I'm new with DSC so apologizes if there is something I'm doing wrong here. I have written a simple configuration, it is something like this:

```
configuration IISConfigurationDSC
{ 
    param 
    ( 
        # Target nodes to apply the configuration 
        [string[]]$NodeName = 'localhost',
        [string[]]$secureFolder = 'E:\Web_secureNO2\' 
    ) 
    # Import the module that defines custom resources 
    Import-DscResource -Module xWebAdministration 
    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node localhost
    {
        xWebAppPool secureAppPool
        {
            Name   = "secure2"
            Ensure = "Present"
            State  = "Started"
        }

        File wwwroot_secure
        {
            Type = "Directory"
            Ensure = "Present"
            DestinationPath = "$($secureFolder)wwwroot_secure"
        }

        xWebsite secureSite
        { 
            Ensure          = "Present" 
            Name            = "secure2" 
            ApplicationPool = "secure"
            State           = "Started" 
            PhysicalPath    = "$($secureFolder)wwwroot_secure"
            BindingInfo     = MSFT_xWebBindingInformation
                 {
                   Protocol              = "HTTP"
                   Port                  = 81
                 }
            DependsOn       = @("[xWebAppPool]secureAppPool","[File]wwwroot_secure")
        }
    }
}
```

I get this error saying "Cannot find path 'IIS:\Sites\secure2' because it does not exist.", obvious...

I took a quick look at the MSFT_xWebSite.psm1 module and I find line 404

```
$Website = Get-Website -Name $Name
```

This command returns all sites, for some reason the -Name parameter does not work. It should have a where statement to be able to filter the appropiate WebSite

```
$Website = Get-Website | where name -eq $Name
```

Is there anybody experiencing the same issue?

**Comment by tysonjhayes** [comment]
Hi @josemaparicio I think I've seen this before, but I'm spacing what was going on. What OS are you runnign this on?

**Comment by josemaparicio** [comment]
Hi,

I'm running the script in a Windows Server 2008R2 with powershell 5. I've tested in a Windows Server 2012 R2 and it worked just fine without the where statement!

**Comment by tysonjhayes** [comment]
What version of the resource are you using? I'm showing the dev version has those lines as:
    $Website = Get-Website | Where-Object -FilterScript {
        $_.Name -eq $Name
    }

Also I remember rewriting that to work with 2008R2 as I ran into that problem as well. Could you try updating to the dev version and see if the problem goes away?

**Comment by josemaparicio** [comment]
Hi,

I downloaded 1.7.0.0 from the powershell gallery, should have cloned the repository but I thought the version from the gallery was good enough. I tried the repo version and it worked ok. I will use the github version from now on. Thanks for your help :)

Regards,
Jose.

**Comment by tysonjhayes** [comment]
Ah, I think it's been a while since we've published (I have some PRs open that'll help with that) so the gallery might be a bit out of date. Glad to hear we've got you fixed up. I'm going to close this feel free to open a new issue if you run into another problem.
