### ISSUE TITLE
MSFT_xIISFeatureDelegation - Missing Set-TargetResource Tests

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xWebAdministration#79]
Looks like I forgot to write them and didn't notice on the merge. We'll want to get those tested.

**Comment by rosberglinhares** [comment]
These tests were already written in this commit: 5a5f05de1f7e0077d66b32397f4299b970ed727a. Could we close this issue?

**Comment by johlju** [comment]
Closing this issue as solved.
