### ISSUE TITLE
xWebsite: Resource should check if there's conflicting website running

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xWebAdministration#83]
Per @KarolKaczmarek,

STEPS:

* run following config (it creates IIS which means there will be Default Web Site started)
```PowerShell
configuration webconfig
{

Import-DscResource -Module xWebAdministration

Node localhost {

# Install the IIS role
WindowsFeature IIS
{
Ensure = "Present"
Name = "Web-Server"
}

# Copy the website content
File WebContent
{
Ensure = "Present"
SourcePath = "C:\test\testwebsite"
DestinationPath = "C:\inetpub\FourthCoffee"
Recurse = $true
Type = "Directory"
} 

xWebsite FrontEndSite
{
Ensure = "Present"
Name = "FourthCoffee"
PhysicalPath = "c:\inetpub\FourthCoffee"
State = "Started"
#BindingInfo = MSFT_xWebBindingInformation {Port="80"}
DependsOn = "[File]WebContent"
}

}

}
webconfig
```
* Call: `Start-DscOperation -path .\webconfig -wait -verbose`
(it will fail to start the new website because default web site is already running and there's conflict)

EXPECTED RESULT:
we should get error that we cannot start a new website because of bindings conflict where there is already a site running on the same IP address and port.
Error could also suggest to stop those conflicting websites using `Stop-Website` cmdlet. 

ACTUAL RESULT:
"InvalidOperation" error which doesn't help much:
```
PowerShell DSC resource MSFT_xWebsite failed to execute Set-TargetResource functionality with error message:
+ CategoryInfo : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : ProviderOperationExecutionFailure
+ PSComputerName : localhost

The SendConfigurationApply function did not succeed.
+ CategoryInfo : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : MI RESULT 1
+ PSComputerName : localhost
```

Per @jianyunt,

The issue was partially fixed:

1. if a user privides BindingInfo (`BindingInfo = MSFT_xWebBindingInformation {Port="80"}`) in the configuration, and then try to create a new website Let's say FourthCoffee4, a proper error messages shows - Fixed

2. if a user does not provide Bindinginfo in the configuration, the issue repro's, meaning no proper error message shows. Only the following. - Not fixed.

PowerShell provider MSFT_xWebsite failed to execute Set-TargetResource functionality with error message:
```
+ CategoryInfo : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : ProviderOperationExecutionFailure
+ PSComputerName : localhost
VERBOSE: [TestMachineName]: LCM: [ End Set ]
The SendConfigurationApply function did not succeed.
+ CategoryInfo : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : MI RESULT 1
+ PSComputerName : localhost
```

**Comment by SNikalaichyk** [comment]
Hello all,
I can implement it as I am already very familiar with xWebsite.

**Comment by TravisEz13** [comment]
@SNikalaichyk  Thanks

**Comment by tysonjhayes** [comment]
Closing as this code was merged.
