### ISSUE TITLE
PhysicalPath parameter not consistent in xWebsite

### ISSUE THREAD

**Issue by gpduck** [PowerShell/xWebAdministration#9]
The PhysicalPath property is marked as "Mandatory" on Set-TargetResource, but "write" in the MOF.  This is misleading when you look at the help generated in the ISE and results in the somewhat difficult to troubleshoot error message:

>PowerShell DSC resource MSFT_xWebsite  failed to execute Test-TargetResource functionality with error message: PowerShell Desired State Configuration does not support execution of
commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.

**Comment by tysonjhayes** [comment]
Fortunately this is an easy fix, unfortunately we don't have much in the way of unit testing on this module so it'll take more time to bootstrap up the test infastructure then it will to actually correct the problem. :grinning:

What we should decide on is if it should be required or not.

If we change the mof file to Required (which would remove the warning) we'd have to add it to the Get-TargetResource which personally I find a bit gross as we don't actually use the physical path.

If we actually remove the required parameter on the file we then have no way of enforcing (short of checking that the variable is null and throwing, which makes me think it should just be required. So I guess adding it to Get-TargetResource is the "better" option?

**Comment by TravisEz13** [comment]
I agree with @tysonjhayes final analysis.  Physical-Path should be required.  Perhaps it's an issue in DSC that anything other than the key properties are required for Get-TargetResource.  Theoretically, only the key properties should be needed to get the resources.

**Comment by tysonjhayes** [comment]
@TravisEz13 I've got a fix for this already and can copy/paste some of my tests from xNetworking to get this going pretty quickly. Should have something I can give back by tomorrow or so (assuming appveyor plays nice with me).

**Comment by tysonjhayes** [comment]
OK so this is actually blocked on [xDSCResourceDesigner](https://github.com/PowerShell/xDSCResourceDesigner/issues/14) having a bug in the embedded classes.  This is fixed in the cDSCResourceDesigner. So I won't be able to test this until the bug in xDSCResourceDesigner is fixed. @TravisEz13 do we want to wait until xDSCResourceDesigner is fixed for me to submit this or should I go ahead?

**Comment by TravisEz13** [comment]
blocked because you cannot write proper tests?

How about we add placeholder tests for the resource designer tests and add a test that tries to calls a configuration without the parameter, and verify it throws.  Example with the Registry Resource, and the ValueName parameter missing:

```
Describe -Name 'Example' -Fixture {
    it -name 'ExampleIt' -test {

           configuration ExampleConfig
            {
                Import-DscResource –ModuleName ’PSDesiredStateConfiguration’
                Registry ExampleFile
                {
                    Key = 'keyExample'
                }
            }

        {
            ExampleConfig
            
        } | should throw "Errors occurred while processing configuration 'ExampleConfig'."
    }
}
```
