### ISSUE TITLE
xWebsite incorrectly validates that port is unique across site bindings

### ISSUE THREAD

**Issue by Richiban** [PowerShell/xWebAdministration#93]
This is a regression introduced in 1441fded306cdf652cdbcfacb6092a819f72b3e1.

The function Test-BindingInfo asserts for "standard" bindings (i.e. http and https) that the port number is unique across bindings; this is incorrect. It is perfectly valid (and what we are trying to do at the moment) to have multiple bindings on the same port that differ by host header.

What it should actually do is assert that the combination of port and hostname is unique.

**Comment by tysonjhayes** [comment]
@SNikalaichyk - could you take a look?

**Comment by SNikalaichyk** [comment]
@tysonjhayes This should be fixed in #88.

**Comment by tysonjhayes** [comment]
Sorry about that, I've been pretty busy. #88 was merged, @Richiban could you merge to dev and see if the problem is resolved?

**Comment by tysonjhayes** [comment]
Howdy. I'm going to resolve this as we did make a change, please reopen if you are still seeing some issues.
