### ISSUE TITLE
xWebAppPool InvalidCastToXmlDocument

### ISSUE THREAD

**Issue by SNikalaichyk** [PowerShell/xWebAdministration#96]
The **Get-TargetResource** and the **Test-TargetResource** functions in the **xWebAppPool** resource may fail on trying to cast **appcmd.exe** XML string output to an **XmlDocument**. For example if application pool user has "**<**" in its password.
I think this bug may be interrelated with #92 (**UPDATE:** it was not related).

Error:
```powershell
Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "'<', hexadecimal value 0x3C, is an
invalid attribute character. Line 2, position 90."
At line:1 char:1
+ [xml] $PoolConfig = Invoke-AppCmd -Arguments list,apppool,$Name,/conf ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
```

Event Log Entry:
```
This event indicates that a non-terminating error was thrown when DSCEngine was executing Test-TargetResource on MSFT_xWebAppPool DSC resource. FullyQualifiedErrorId is InvalidCastToXmlDocument. Error Message is Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "'<', hexadecimal value 0x3C, is an invalid attribute character. Line 2, position 90.".
```

**Comment by SNikalaichyk** [comment]
I'll take care of fixing this bug as well as fixing #92.

**Comment by SNikalaichyk** [comment]
This issue should be fixed in #98.

**Comment by schwaizi** [comment]
I still have similar issue. Tested using password contains letters and numbers.

Error:
This event indicates that a non-terminating error was thrown when DSCEngine was executing Test-TargetResource on MSFT_xWebAppPool DSC resource. FullyQualifiedErrorId is InvalidCastToXmlDocument. Error Message is Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "An error occurred while parsing EntityName. Line 2, position 96.".

**Comment by SNikalaichyk** [comment]
@schwaizi,
The PR #98 hasn't been merged yet.

**Comment by schwaizi** [comment]
true :)

well, i got rid of the message by specifying more values in case someone need workaround urgently

xWebAppPool ASM
{
	Name = "TestPool"
	Ensure = "Present"
	enable32BitAppOnWin64 = $true
	autoStart = $true
	managedRuntimeVersion = "v4.0"
	managedPipelineMode = "Integrated"
	startMode = "AlwaysRunning"
	LoadUserProfile = $false
	IdentityType = "SpecificUser"
	Credential = $WebCredentials
	restartSchedule = @()
}

**Comment by tysonjhayes** [comment]
Closing this as the PR was merged. Please reopen if we are still having issues.
